#line 1 "Lexer.C"

#line 3 "Lexer.C"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define epddl__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer epddl__create_buffer
#endif

#ifdef yy_delete_buffer
#define epddl__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer epddl__delete_buffer
#endif

#ifdef yy_scan_buffer
#define epddl__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer epddl__scan_buffer
#endif

#ifdef yy_scan_string
#define epddl__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string epddl__scan_string
#endif

#ifdef yy_scan_bytes
#define epddl__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes epddl__scan_bytes
#endif

#ifdef yy_init_buffer
#define epddl__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer epddl__init_buffer
#endif

#ifdef yy_flush_buffer
#define epddl__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer epddl__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define epddl__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state epddl__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define epddl__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer epddl__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define epddl_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state epddl_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define epddl_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state epddl_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define epddl_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack epddl_ensure_buffer_stack
#endif

#ifdef yylex
#define epddl_lex_ALREADY_DEFINED
#else
#define yylex epddl_lex
#endif

#ifdef yyrestart
#define epddl_restart_ALREADY_DEFINED
#else
#define yyrestart epddl_restart
#endif

#ifdef yylex_init
#define epddl_lex_init_ALREADY_DEFINED
#else
#define yylex_init epddl_lex_init
#endif

#ifdef yylex_init_extra
#define epddl_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra epddl_lex_init_extra
#endif

#ifdef yylex_destroy
#define epddl_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy epddl_lex_destroy
#endif

#ifdef yyget_debug
#define epddl_get_debug_ALREADY_DEFINED
#else
#define yyget_debug epddl_get_debug
#endif

#ifdef yyset_debug
#define epddl_set_debug_ALREADY_DEFINED
#else
#define yyset_debug epddl_set_debug
#endif

#ifdef yyget_extra
#define epddl_get_extra_ALREADY_DEFINED
#else
#define yyget_extra epddl_get_extra
#endif

#ifdef yyset_extra
#define epddl_set_extra_ALREADY_DEFINED
#else
#define yyset_extra epddl_set_extra
#endif

#ifdef yyget_in
#define epddl_get_in_ALREADY_DEFINED
#else
#define yyget_in epddl_get_in
#endif

#ifdef yyset_in
#define epddl_set_in_ALREADY_DEFINED
#else
#define yyset_in epddl_set_in
#endif

#ifdef yyget_out
#define epddl_get_out_ALREADY_DEFINED
#else
#define yyget_out epddl_get_out
#endif

#ifdef yyset_out
#define epddl_set_out_ALREADY_DEFINED
#else
#define yyset_out epddl_set_out
#endif

#ifdef yyget_leng
#define epddl_get_leng_ALREADY_DEFINED
#else
#define yyget_leng epddl_get_leng
#endif

#ifdef yyget_text
#define epddl_get_text_ALREADY_DEFINED
#else
#define yyget_text epddl_get_text
#endif

#ifdef yyget_lineno
#define epddl_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno epddl_get_lineno
#endif

#ifdef yyset_lineno
#define epddl_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno epddl_set_lineno
#endif

#ifdef yyget_column
#define epddl_get_column_ALREADY_DEFINED
#else
#define yyget_column epddl_get_column
#endif

#ifdef yyset_column
#define epddl_set_column_ALREADY_DEFINED
#else
#define yyset_column epddl_set_column
#endif

#ifdef yywrap
#define epddl_wrap_ALREADY_DEFINED
#else
#define yywrap epddl_wrap
#endif

#ifdef yyget_lval
#define epddl_get_lval_ALREADY_DEFINED
#else
#define yyget_lval epddl_get_lval
#endif

#ifdef yyset_lval
#define epddl_set_lval_ALREADY_DEFINED
#else
#define yyset_lval epddl_set_lval
#endif

#ifdef yyget_lloc
#define epddl_get_lloc_ALREADY_DEFINED
#else
#define yyget_lloc epddl_get_lloc
#endif

#ifdef yyset_lloc
#define epddl_set_lloc_ALREADY_DEFINED
#else
#define yyset_lloc epddl_set_lloc
#endif

#ifdef yyalloc
#define epddl_alloc_ALREADY_DEFINED
#else
#define yyalloc epddl_alloc
#endif

#ifdef yyrealloc
#define epddl_realloc_ALREADY_DEFINED
#else
#define yyrealloc epddl_realloc
#endif

#ifdef yyfree
#define epddl_free_ALREADY_DEFINED
#else
#define yyfree epddl_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define epddl_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[629] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   95,   93,   92,   92,    1,    2,   39,   91,
       93,   86,   37,   36,   38,   93,   88,   88,   30,   31,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   24,   25,   94,   91,   41,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   86,   90,   40,   88,   88,   87,   89,
       87,   87,   87,   66,   87,   87,   87,   87,   87,   73,
       87,   87,   87,   79,   87,   87,   87,   87,   87,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   90,   90,   63,   87,   65,
       87,   87,   87,   87,   87,   74,   87,   87,   87,   78,
       87,   87,   87,   87,   84,   87,    0,    0,    0,   43,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       85,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   35,   28,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   64,   87,   87,   87,   70,   87,   87,
       75,   87,   87,   87,   87,   87,   87,    0,    0,    0,
        0,    0,    0,    0,   19,    0,    0,    0,    0,    0,
       32,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    0,    0,    0,   11,    0,   67,   68,   69,
       71,   87,   87,   87,   87,   87,   87,   87,    9,    0,
       22,    0,    0,   21,    0,    0,   16,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   27,   44,    0,    0,   33,   72,   76,

       77,   87,   87,   87,   83,    0,    0,    0,    0,    0,
        0,    0,    0,   55,    0,    0,    0,    0,   26,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   87,
       87,   87,    0,    0,    0,    0,    0,   45,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   80,   87,   82,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   17,    0,    0,   34,   87,    0,    0,    0,
        0,   18,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    7,   29,    0,    0,    0,   10,
        0,    0,    6,    0,    0,   87,    0,   12,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       87,    0,    0,   23,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   52,    0,
        0,   13,    4,    0,    0,   81,    0,    0,    0,    0,
        0,    0,    0,    0,   56,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   20,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   57,    0,    0,    0,    0,    0,    0,
        0,   46,    0,    0,    0,    0,   53,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   42,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       15,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       48,    0,    0,    0,    0,    0,    0,   62,    0,    0,
        0,   50,    0,    0,    0,    0,    0,   47,   58,    0,
        0,    0,   51,    0,    8,    0,    3,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       59,    0,    0,    0,    0,   54,    0,    0,   14,   49,
        0,    0,    0,    0,    0,   60,   61,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    5,
        6,    1,    1,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,   12,
       13,   14,   15,    1,   16,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,    1,   19,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    5,    1,
        1,    1,    1,    1,    1,    6,    6,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1
    } ;

static const flex_int16_t yy_base[635] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  972,  973,  973,  973,  973,  973,  973,  962,
       39,    0,  973,  973,  973,  950,  937,    0,  973,  973,
       49,   47,   81,   50,   82,   87,   89,   88,  106,  107,
      127,  117,  973,  973,  973,  959,  973,   29,  932,   87,
       92,  928,  930,  930,   38,   65,  103,  938,  922,  916,
      926,  938,   70,    0,   80,  973,    0,  926,  145,  973,
      146,  152,  154,  153,  155,  160,  163,  178,  180,  181,
      183,  186,  191,  201,  208,  209,  219,  226,  229,  917,
      931,  922,  101,  921,  919,  911,  926,  921,  928,  927,

      918,  132,  922,   89,  905,  906,  904,  917,  111,  920,
      904,  910,  906,  912,  898,  200,  218,    0,  237,  239,
      247,  248,  254,  257,  271,  274,  277,  279,  280,  282,
      299,  302,  307,  308,  317,  325,  906,  900,  900,  973,
      903,  910,  909,  908,  894,  888,  893,  893,  884,  884,
      893,  239,  896,  895,  890,  897,  877,  146,  895,  874,
      874,  289,  871,  871,  873,  878,  328,  331,  349,  336,
      339,  350,  359,  367,  369,  376,  377,  384,  390,  391,
      397,  874,  868,  872,  879,  876,  871,  871,  862,  861,
      875,  973,  973,  859,  865,  865,  864,  872,  856,  870,

      859,  868,  855,  860,  848,  858,  857,  846,  850,  858,
      861,  856,  856,  398,  405,  412,  418,  420,  423,  429,
      431,  440,  446,  448,  454,  461,  455,  845,  233,  844,
      843,  842,  846,  845,  834,  847,  864,  849,  828,  195,
      861,  827,  824,  858,  839,  828,  828,  838,  831,  821,
      835,  973,  830,  818,  815,  973,  815,  468,  475,  478,
      486,  488,  493,  495,  496,  503,  510,  513,  846,  825,
      973,  844,  829,  973,  826,  808,  973,  813,  811,  807,
      811,  807,  802,  807,  801,  818,  815,  797,  802,  811,
      813,  798,  807,  973,  973,  792,  801,  973,  516,  524,

      531,  537,  539,  544,  545,  789,  790,  796,  786,  818,
      779,  783,  796,  814,  813,  197,  790,  797,  973,  795,
      788,  790,  790,  784,  772,  777,  777,  788,  773,  546,
      552,  554,  762,  771,  771,  779,  780,  973,  773,  794,
      547,  217,  761,  774,  773,  764,  767,  774,  756,  764,
      752,  766,  751,  764,  756,  753,  579,  581,  584,  750,
      744,  749,  759,  747,  760,  742,  745,  749,  743,  751,
      740,  260,  734,  750,  733,  746,  738,  735,  313,  728,
      738,  727,  973,  731,  757,  973,  586,  737,  737,  725,
      717,  973,  726,  726,  732,  722,  721,  714,  719,  728,

      712,  725,  726,  713,  973,  973,  718,  719,  713,  973,
      715,  708,  973,  702,   35,  589,  706,  733,  700,  706,
      704,  729,  709,  699,  704,  703,  692,  709,  689,  705,
      692,  692,  685,  699,  694,  687,  687,  681,  684,  683,
      592,  679,  684,  973,  690,  679,  687,  687,  670,  670,
      686,  679,  675,  683,  670,  670,  679,  657,  973,  662,
      666,  973,  973,  661,  659,  594,  664,  667,  671,  660,
      658,  654,  657,  669,  973,  655,  681,  652,  652,  661,
      655,  676,  642,  642,  647,  639,  637,  655,  649,  668,
      636,  648,  649,  633,  643,  645,  634,  643,  637,  625,

      311,  625,  973,  622,  639,  629,  622,  634,  627,  624,
      622,  630,  609,  973,  628,  628,  622,  610,  620,  611,
      596,  973,  593,  588,  601,  599,  973,  585,  577,  594,
      583,  606,  575,  581,  568,  578,  570,  569,  560,  559,
      544,  973,  539,  540,  538,  544,  542,  521,  515,  502,
      511,  499,  495,  502,  481,  494,  488,  481,  462,  481,
      973,  459,  459,  457,  448,  438,  437,  431,  435,  417,
      973,  418,  420,  410,  416,  396,  409,  973,  394,  387,
      369,  973,  363,  354,  351,  347,  358,  973,  973,  339,
      338,  327,  973,  333,  973,  332,  973,  336,  317,  310,

      339,  306,  291,  296,  268,  301,  277,  255,  246,  248,
      973,  239,  217,  186,  176,  973,  189,  161,  973,  973,
      160,  139,  111,  102,   76,  973,  973,  973,  626,  632,
       44,  634,  638,  642
    } ;

static const flex_int16_t yy_def[635] =
    {   0,
      628,    1,  629,  629,  629,  629,  629,  629,  629,  629,
      629,  629,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  630,  628,  628,  628,  631,  632,  632,  628,  628,
      633,  633,  633,  633,  633,  633,  633,  633,  633,  633,
      633,  633,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  630,  634,  628,  632,  632,  633,  628,
      633,  633,  633,  633,  633,  633,  633,  633,  633,  633,
      633,  633,  633,  633,  633,  633,  633,  633,  633,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  634,  634,  632,  633,  633,
      633,  633,  633,  633,  633,  633,  633,  633,  633,  633,
      633,  633,  633,  633,  633,  633,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  633,  633,  633,  633,
      633,  633,  633,  633,  633,  633,  633,  633,  633,  633,
      633,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  633,  633,  633,  633,  633,  633,  633,
      633,  633,  633,  633,  633,  633,  633,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  633,  633,  633,
      633,  633,  633,  633,  633,  633,  633,  633,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  633,  633,

      633,  633,  633,  633,  633,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  633,
      633,  633,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  633,  633,  633,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  633,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  633,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      633,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  633,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,    0,  628,  628,
      628,  628,  628,  628
    } ;

static const flex_int16_t yy_nxt[1022] =
    {   0,
       14,   15,   16,   14,   17,   18,   19,   14,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   14,
       31,   32,   32,   33,   34,   35,   32,   32,   36,   32,
       32,   37,   32,   38,   39,   40,   32,   32,   41,   42,
       32,   32,   32,   32,   32,   32,   43,   44,   47,   65,
       69,   90,   69,   69,   70,   91,   70,   70,  102,   48,
      439,   49,   50,   51,   52,   53,   69,   54,   69,   69,
      440,   55,  103,   56,   57,   72,   58,   59,   60,   61,
       62,   63,   73,  116,   69,   69,  104,   74,   70,   70,
       69,   69,   69,   77,   70,   70,   70,  114,  105,  116,

       69,   69,   78,  627,  115,   75,   69,   69,   69,   69,
       69,   93,   80,   70,   70,   76,   79,   82,  153,   81,
       69,   94,   83,  106,   70,   69,   69,  154,   96,  626,
       69,   95,  140,   97,   70,   98,   69,  107,  150,  141,
      108,   86,  159,   84,   87,   85,   69,  160,   69,   69,
      625,   88,   70,   70,   89,   69,   69,   69,   69,   70,
       70,   70,   70,   69,   69,   69,   69,   70,  203,  204,
       70,   69,   69,   69,   69,  151,  119,  120,  624,   69,
      121,   69,   69,   69,   69,   70,   69,   70,   70,   69,
       70,  123,  122,   70,   69,  623,  622,   69,   70,   69,

       69,  282,   69,  116,   69,   69,  126,  128,   70,  124,
       69,   69,   69,  621,  620,   70,   70,  125,  127,  116,
       69,  116,   69,  283,  619,  129,   70,   69,   69,   69,
      130,  343,   69,   70,  344,  131,   70,  116,   69,  270,
       69,  618,   69,  133,   70,   69,   70,  132,   69,  371,
       69,   69,  372,  134,   70,   70,   69,   69,   69,  196,
       69,   70,  617,  197,   70,  135,   69,   69,  169,  136,
      167,  271,  616,   69,   69,  168,   69,   69,   70,  615,
       69,   70,   69,   69,   70,   69,   70,   70,  614,   70,
       69,  172,  170,   69,  401,  171,   69,  402,   69,   69,

      613,   69,   69,  173,  176,   69,   70,  612,  174,   70,
       69,   69,  611,  208,   70,   70,  175,  209,   69,  409,
       69,   69,  610,  177,   70,  609,   69,   69,   69,  180,
      179,   69,   70,  520,   69,   70,   69,  521,   70,   69,
      608,  178,   69,   70,   69,  607,   70,   69,  606,  181,
       69,  410,   69,   69,  605,   69,   70,   70,   69,  604,
      603,  602,   69,  218,  215,  601,   70,  214,   69,   69,
       69,  600,   69,  599,   70,  217,   70,  216,   69,   69,
       69,  219,  598,   70,   70,  597,   69,   69,   69,  222,
      596,   70,  595,   69,   69,   69,   69,   70,   70,  220,

       69,   69,  594,   69,   70,   70,  225,  593,   69,   69,
       69,  221,   70,  223,  224,   69,   69,   69,  226,   70,
      592,   69,  227,   69,   69,   70,   69,   70,  591,  258,
       70,   69,   69,  590,   69,  589,   70,   69,   70,   69,
      588,  587,   69,   69,  586,  259,  585,   70,   69,   69,
       69,   69,  584,   70,  261,   70,  260,   69,   69,   69,
      262,   70,   70,  583,   69,   69,  264,   69,   70,  582,
      581,   69,  580,   69,   69,   70,  579,  263,   69,  268,
       69,   69,   70,  267,  578,   70,  577,   69,  266,   69,
      265,   69,  576,   70,   69,   70,   69,   69,   69,   69,

       70,  575,   70,   70,  574,   69,   69,   69,  299,  573,
       70,  572,   69,   69,   69,   69,   69,   70,  571,   69,
       70,  570,   69,   70,  302,  569,  301,   69,  568,   69,
      304,   70,   69,  567,   69,   69,  303,  300,   70,  566,
       69,  565,   69,   69,   70,  305,   70,   69,   69,   69,
       69,   70,   70,   70,  564,   69,   69,   69,   69,   70,
      563,   70,  331,   69,   69,   69,  562,  367,  561,  560,
      357,   69,  368,   69,  559,  330,  558,  557,  359,  556,
      358,  369,   69,  332,   69,  370,   70,   69,   70,   69,
      388,   70,   69,   70,  555,   69,   70,   69,   69,   70,

       69,   70,  554,   69,  553,   69,  552,  551,   69,  550,
      549,   69,  548,   69,  416,  547,  546,  545,  544,  543,
      387,  542,  541,  441,  540,  466,   45,   45,   45,   45,
       45,   45,   64,  539,   64,   64,   64,   64,   67,   67,
       71,   71,   71,   71,  117,  538,  117,  117,  537,  536,
      535,  534,  533,  532,  531,  530,  529,  528,  527,  526,
      525,  524,  523,  522,  519,  518,  517,  516,  515,  514,
      513,  512,  511,  510,  509,  508,  507,  506,  505,  504,
      503,  502,  501,  500,  499,  498,  497,  496,  495,  494,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  484,

      483,  482,  481,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  415,  414,  413,  412,  411,  408,  407,
      406,  405,  404,  403,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,

      366,  365,  364,  363,  362,  361,  360,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  269,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,

      236,  235,  234,  233,  232,  231,  230,  229,  228,  213,
      212,  211,  210,  207,  206,  205,  202,  201,  200,  199,
      198,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  166,  165,  164,  163,  162,
      161,  158,  157,  156,  155,  152,  149,  148,  147,  146,
      145,  144,  143,  142,  139,  138,  137,  118,  113,  112,
      111,  110,  109,  101,  100,   99,   92,   46,   68,   66,
       46,  628,   13,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628
    } ;

static const flex_int16_t yy_chk[1022] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   21,  631,
       32,   48,   31,   34,   32,   48,   31,   34,   55,   21,
      415,   21,   21,   21,   21,   21,   32,   21,   31,   34,
      415,   21,   55,   21,   21,   31,   21,   21,   21,   21,
       21,   21,   31,   65,   33,   35,   56,   31,   33,   35,
       36,   38,   37,   34,   36,   38,   37,   63,   56,   65,

       33,   35,   35,  625,   63,   33,   36,   38,   37,   39,
       40,   50,   36,   39,   40,   33,   35,   37,  104,   36,
       42,   50,   38,   57,   42,   39,   40,  104,   51,  624,
       41,   50,   93,   51,   41,   51,   42,   57,  102,   93,
       57,   40,  109,   39,   40,   39,   41,  109,   69,   71,
      623,   41,   69,   71,   42,   72,   74,   73,   75,   72,
       74,   73,   75,   76,   69,   71,   77,   76,  158,  158,
       77,   72,   74,   73,   75,  102,   72,   73,  622,   76,
       75,   78,   77,   79,   80,   78,   81,   79,   80,   82,
       81,   77,   76,   82,   83,  621,  618,   78,   83,   79,

       80,  240,   81,  116,   84,   82,   80,   82,   84,   78,
       83,   85,   86,  617,  615,   85,   86,   79,   81,  116,
       84,  117,   87,  240,  614,   82,   87,   85,   86,   88,
       83,  316,   89,   88,  316,   85,   89,  117,   87,  229,
      119,  613,  120,   87,  119,   88,  120,   86,   89,  342,
      121,  122,  342,   87,  121,  122,  119,  123,  120,  152,
      124,  123,  612,  152,  124,   88,  121,  122,  122,   89,
      119,  229,  610,  123,  125,  121,  124,  126,  125,  609,
      127,  126,  128,  129,  127,  130,  128,  129,  608,  130,
      125,  125,  123,  126,  372,  124,  127,  372,  128,  129,

      607,  130,  131,  125,  129,  132,  131,  606,  127,  132,
      133,  134,  605,  162,  133,  134,  128,  162,  131,  379,
      135,  132,  604,  131,  135,  603,  133,  134,  136,  134,
      133,  167,  136,  501,  168,  167,  135,  501,  168,  170,
      602,  132,  171,  170,  136,  601,  171,  167,  600,  136,
      168,  379,  169,  172,  599,  170,  169,  172,  171,  598,
      596,  594,  173,  171,  168,  592,  173,  167,  169,  172,
      174,  591,  175,  590,  174,  170,  175,  169,  173,  176,
      177,  172,  587,  176,  177,  586,  174,  178,  175,  175,
      585,  178,  584,  179,  180,  176,  177,  179,  180,  173,

      181,  214,  583,  178,  181,  214,  178,  581,  215,  179,
      180,  174,  215,  176,  177,  216,  181,  214,  179,  216,
      580,  217,  180,  218,  215,  217,  219,  218,  579,  215,
      219,  216,  220,  577,  221,  576,  220,  217,  221,  218,
      575,  574,  219,  222,  573,  216,  572,  222,  220,  223,
      221,  224,  570,  223,  219,  224,  217,  225,  227,  222,
      220,  225,  227,  569,  226,  223,  223,  224,  226,  568,
      567,  258,  566,  225,  227,  258,  565,  222,  259,  227,
      226,  260,  259,  226,  564,  260,  563,  258,  225,  261,
      224,  262,  562,  261,  259,  262,  263,  260,  264,  265,

      263,  560,  264,  265,  559,  261,  266,  262,  262,  558,
      266,  557,  263,  267,  264,  265,  268,  267,  556,  299,
      268,  555,  266,  299,  265,  554,  264,  300,  553,  267,
      267,  300,  268,  552,  301,  299,  266,  263,  301,  551,
      302,  550,  303,  300,  302,  268,  303,  304,  305,  330,
      301,  304,  305,  330,  549,  331,  302,  332,  303,  331,
      548,  332,  303,  304,  305,  330,  547,  341,  546,  545,
      330,  331,  341,  332,  544,  302,  543,  541,  332,  540,
      331,  341,  357,  304,  358,  341,  357,  359,  358,  387,
      359,  359,  416,  387,  539,  441,  416,  466,  357,  441,

      358,  466,  538,  359,  537,  387,  536,  535,  416,  534,
      533,  441,  532,  466,  387,  531,  530,  529,  528,  526,
      358,  525,  524,  416,  523,  441,  629,  629,  629,  629,
      629,  629,  630,  521,  630,  630,  630,  630,  632,  632,
      633,  633,  633,  633,  634,  520,  634,  634,  519,  518,
      517,  516,  515,  513,  512,  511,  510,  509,  508,  507,
      506,  505,  504,  502,  500,  499,  498,  497,  496,  495,
      494,  493,  492,  491,  490,  489,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  479,  478,  477,  476,  474,
      473,  472,  471,  470,  469,  468,  467,  465,  464,  461,

      460,  458,  457,  456,  455,  454,  453,  452,  451,  450,
      449,  448,  447,  446,  445,  443,  442,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  414,  412,  411,  409,  408,  407,  404,  403,  402,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  391,
      390,  389,  388,  385,  384,  382,  381,  380,  378,  377,
      376,  375,  374,  373,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,

      340,  339,  337,  336,  335,  334,  333,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  318,  317,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  297,
      296,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  276,  275,  273,
      272,  270,  269,  257,  255,  254,  253,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  228,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  191,

      190,  189,  188,  187,  186,  185,  184,  183,  182,  166,
      165,  164,  163,  161,  160,  159,  157,  156,  155,  154,
      153,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  139,  138,  137,  115,  114,  113,  112,  111,
      110,  108,  107,  106,  105,  103,  101,  100,   99,   98,
       97,   96,   95,   94,   92,   91,   90,   68,   62,   61,
       60,   59,   58,   54,   53,   52,   49,   46,   27,   26,
       20,   13,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "epddl.l"
/* -*- c++ -*- File generated by the BNF Converter (bnfc 2.9.4). */
/* Lexer definition for use with FLex */
#define YY_NO_INPUT 1
#line 9 "epddl.l"
#include "Absyn.H"
#include "Bison.H"

#define initialize_lexer epddl__initialize_lexer

static void update_loc(YYLTYPE* loc, char* text)
{
  loc->first_line = loc->last_line;
  loc->first_column = loc->last_column;
  int i = 0;
  for (; text[i] != '\0'; ++i) {
      if (text[i] == '\n') {
          ++loc->last_line;
          loc->last_column = 0;
      } else {
          ++loc->last_column;
      }
  }
}
#define YY_USER_ACTION update_loc(yylloc, yytext);

#line 1114 "Lexer.C"

#line 1116 "Lexer.C"

#define INITIAL 0
#define CHAR 1
#define CHARESC 2
#define CHAREND 3
#define STRING 4
#define ESCAPED 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 39 "epddl.l"


#line 1406 "Lexer.C"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 629 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 973 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "epddl.l"
return _LPAREN;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "epddl.l"
return _RPAREN;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "epddl.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "epddl.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "epddl.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "epddl.l"
return _SYMB_5;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "epddl.l"
return _SYMB_6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "epddl.l"
return _SYMB_7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "epddl.l"
return _SYMB_8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "epddl.l"
return _SYMB_9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "epddl.l"
return _SYMB_10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "epddl.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "epddl.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "epddl.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "epddl.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "epddl.l"
return _SYMB_15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "epddl.l"
return _SYMB_16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "epddl.l"
return _SYMB_17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "epddl.l"
return _SYMB_18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "epddl.l"
return _SYMB_19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "epddl.l"
return _SYMB_20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "epddl.l"
return _SYMB_21;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "epddl.l"
return _SYMB_22;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "epddl.l"
return _LBRACE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "epddl.l"
return _RBRACE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "epddl.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "epddl.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "epddl.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "epddl.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "epddl.l"
return _LBRACK;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "epddl.l"
return _RBRACK;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "epddl.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "epddl.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "epddl.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "epddl.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "epddl.l"
return _EQ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "epddl.l"
return _LT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "epddl.l"
return _GT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "epddl.l"
return _MINUS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "epddl.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "epddl.l"
return _DCOLON;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "epddl.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "epddl.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "epddl.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "epddl.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "epddl.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "epddl.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "epddl.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "epddl.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "epddl.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "epddl.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "epddl.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "epddl.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "epddl.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "epddl.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "epddl.l"
return _SYMB_55;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "epddl.l"
return _SYMB_56;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "epddl.l"
return _SYMB_57;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "epddl.l"
return _SYMB_58;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "epddl.l"
return _SYMB_59;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "epddl.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "epddl.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "epddl.l"
return _KW_All;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "epddl.l"
return _KW_agent;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "epddl.l"
return _KW_and;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "epddl.l"
return _KW_as;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "epddl.l"
return _KW_define;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "epddl.l"
return _KW_domain;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "epddl.l"
return _KW_exists;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "epddl.l"
return _KW_false;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 111 "epddl.l"
return _KW_forall;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 112 "epddl.l"
return _KW_formula;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 113 "epddl.l"
return _KW_if;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 114 "epddl.l"
return _KW_iff;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 115 "epddl.l"
return _KW_imply;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 116 "epddl.l"
return _KW_library;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 117 "epddl.l"
return _KW_literal;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 118 "epddl.l"
return _KW_not;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 119 "epddl.l"
return _KW_or;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "epddl.l"
return _KW_otherwise;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 121 "epddl.l"
return _KW_postcondition;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 122 "epddl.l"
return _KW_predicate;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 123 "epddl.l"
return _KW_problem;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 124 "epddl.l"
return _KW_set;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 125 "epddl.l"
return _KW_true;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 127 "epddl.l"
/* skip */; /* BNFC: comment ";" */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 129 "epddl.l"
yylval->_string = strdup(yytext); return T_Name;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 130 "epddl.l"
yylval->_string = strdup(yytext); return T_AgentName;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 131 "epddl.l"
yylval->_string = strdup(yytext); return T_ModalityName;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 132 "epddl.l"
yylval->_string = strdup(yytext); return T_Variable;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 133 "epddl.l"
yylval->_int = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 134 "epddl.l"
/* ignore white space. */;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 135 "epddl.l"
return _ERROR_;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "epddl.l"
ECHO;
	YY_BREAK
#line 1934 "Lexer.C"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 629 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 629 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 628);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 137 "epddl.l"


yyscan_t initialize_lexer(FILE *inp)
{
  yyscan_t scanner;
  if (yylex_init_extra(NULL, &scanner)) return 0;
  if (inp) yyrestart(inp, scanner);
  return scanner;
}


