#line 1 "Lexer.C"

#line 3 "Lexer.C"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define epddl__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer epddl__create_buffer
#endif

#ifdef yy_delete_buffer
#define epddl__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer epddl__delete_buffer
#endif

#ifdef yy_scan_buffer
#define epddl__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer epddl__scan_buffer
#endif

#ifdef yy_scan_string
#define epddl__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string epddl__scan_string
#endif

#ifdef yy_scan_bytes
#define epddl__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes epddl__scan_bytes
#endif

#ifdef yy_init_buffer
#define epddl__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer epddl__init_buffer
#endif

#ifdef yy_flush_buffer
#define epddl__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer epddl__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define epddl__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state epddl__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define epddl__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer epddl__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define epddl_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state epddl_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define epddl_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state epddl_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define epddl_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack epddl_ensure_buffer_stack
#endif

#ifdef yylex
#define epddl_lex_ALREADY_DEFINED
#else
#define yylex epddl_lex
#endif

#ifdef yyrestart
#define epddl_restart_ALREADY_DEFINED
#else
#define yyrestart epddl_restart
#endif

#ifdef yylex_init
#define epddl_lex_init_ALREADY_DEFINED
#else
#define yylex_init epddl_lex_init
#endif

#ifdef yylex_init_extra
#define epddl_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra epddl_lex_init_extra
#endif

#ifdef yylex_destroy
#define epddl_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy epddl_lex_destroy
#endif

#ifdef yyget_debug
#define epddl_get_debug_ALREADY_DEFINED
#else
#define yyget_debug epddl_get_debug
#endif

#ifdef yyset_debug
#define epddl_set_debug_ALREADY_DEFINED
#else
#define yyset_debug epddl_set_debug
#endif

#ifdef yyget_extra
#define epddl_get_extra_ALREADY_DEFINED
#else
#define yyget_extra epddl_get_extra
#endif

#ifdef yyset_extra
#define epddl_set_extra_ALREADY_DEFINED
#else
#define yyset_extra epddl_set_extra
#endif

#ifdef yyget_in
#define epddl_get_in_ALREADY_DEFINED
#else
#define yyget_in epddl_get_in
#endif

#ifdef yyset_in
#define epddl_set_in_ALREADY_DEFINED
#else
#define yyset_in epddl_set_in
#endif

#ifdef yyget_out
#define epddl_get_out_ALREADY_DEFINED
#else
#define yyget_out epddl_get_out
#endif

#ifdef yyset_out
#define epddl_set_out_ALREADY_DEFINED
#else
#define yyset_out epddl_set_out
#endif

#ifdef yyget_leng
#define epddl_get_leng_ALREADY_DEFINED
#else
#define yyget_leng epddl_get_leng
#endif

#ifdef yyget_text
#define epddl_get_text_ALREADY_DEFINED
#else
#define yyget_text epddl_get_text
#endif

#ifdef yyget_lineno
#define epddl_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno epddl_get_lineno
#endif

#ifdef yyset_lineno
#define epddl_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno epddl_set_lineno
#endif

#ifdef yyget_column
#define epddl_get_column_ALREADY_DEFINED
#else
#define yyget_column epddl_get_column
#endif

#ifdef yyset_column
#define epddl_set_column_ALREADY_DEFINED
#else
#define yyset_column epddl_set_column
#endif

#ifdef yywrap
#define epddl_wrap_ALREADY_DEFINED
#else
#define yywrap epddl_wrap
#endif

#ifdef yyget_lval
#define epddl_get_lval_ALREADY_DEFINED
#else
#define yyget_lval epddl_get_lval
#endif

#ifdef yyset_lval
#define epddl_set_lval_ALREADY_DEFINED
#else
#define yyset_lval epddl_set_lval
#endif

#ifdef yyget_lloc
#define epddl_get_lloc_ALREADY_DEFINED
#else
#define yyget_lloc epddl_get_lloc
#endif

#ifdef yyset_lloc
#define epddl_set_lloc_ALREADY_DEFINED
#else
#define yyset_lloc epddl_set_lloc
#endif

#ifdef yyalloc
#define epddl_alloc_ALREADY_DEFINED
#else
#define yyalloc epddl_alloc
#endif

#ifdef yyrealloc
#define epddl_realloc_ALREADY_DEFINED
#else
#define yyrealloc epddl_realloc
#endif

#ifdef yyfree
#define epddl_free_ALREADY_DEFINED
#else
#define yyfree epddl_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define epddl_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[663] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   95,   93,   92,   92,    1,    2,   39,   91,
       93,   86,   37,   36,   38,   93,   88,   88,   30,   31,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   24,   25,   94,   91,   41,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   86,   90,   40,   88,   88,   87,   89,   87,
       87,   87,   67,   87,   87,   87,   87,   73,   87,   87,
       87,   79,   87,   87,   87,   87,   87,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   90,   90,   64,   87,   66,
       87,   87,   87,   87,   74,   87,   87,   87,   78,   87,
       87,   87,   87,   84,   87,    0,    0,    0,   43,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       85,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   35,   28,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   65,   87,   87,   70,   87,
       87,   75,   87,   87,   87,   87,   87,   87,    0,    0,
        0,    0,    0,    0,    0,    0,   19,    0,   27,    0,
        0,    0,    0,   32,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    5,    0,    0,    0,   11,    0,
       68,   69,   71,   87,   87,   87,   87,   87,   87,   87,
        9,    0,   22,    0,    0,    0,   21,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   44,    0,    0,

       33,   72,   76,   77,   87,   87,   87,   83,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   56,    0,    0,
        0,    0,    0,   26,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   87,   87,   87,    0,    0,    0,
        0,    0,    0,   45,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   80,   87,   82,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   17,    0,    0,   34,   87,    0,    0,    0,    0,

       18,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,   29,    0,    0,    0,    0,
       10,    0,    0,    6,    0,    0,   87,    0,   12,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   87,    0,    0,   23,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   53,    0,    0,   13,    4,    0,   81,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   57,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   58,
        0,    0,    0,    0,    0,    0,    0,    0,   46,    0,
        0,    0,   54,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   42,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   63,    0,    0,

        0,   51,    0,    0,    0,    0,    0,    0,    0,    0,
       59,    0,    0,    0,   52,    0,    0,    8,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   47,    0,    0,    0,    0,
        0,   60,    0,    0,    0,   50,    0,   55,    0,    0,
        0,   14,   48,   49,    0,    0,    0,    0,    0,   61,
       62,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    5,
        6,    1,    1,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,   12,
       13,   14,   15,    1,   16,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,    1,   19,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    5,    1,
        1,    1,    1,    1,    1,    6,    6,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1
    } ;

static const flex_int16_t yy_base[669] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  989,  990,  990,  990,  990,  990,  990,  979,
       39,    0,  990,  990,  990,  967,  954,    0,  990,  990,
       49,   47,   81,   82,   87,   89,   88,   90,  107,  118,
      117,  990,  990,  990,  976,  990,   27,  949,  104,  104,
       40,  948,  948,   35,  956,   37,  115,  955,  934,  944,
      956,   77,    0,   80,  990,    0,  944,  127,  990,  136,
      150,  153,  156,  158,  159,  161,  178,  179,  181,  186,
      187,  192,  205,  210,  211,  220,  230,  935,  949,  940,
      120,  933,  938,  936,  928,  943,  938,  943,  944,  943,

      934,   80,  938,  934,  141,  920,  921,  919,  932,   67,
      920,  926,  922,  928,  914,  168,  200,    0,  231,  233,
      239,  253,  244,  258,  250,  268,  273,  276,  278,  295,
      286,  301,  308,  309,  314,  922,  916,  916,  990,  919,
      917,  925,  924,  923,  909,  903,  901,  907,  907,  898,
      898,  907,  242,  914,  909,  908,  903,  910,  890,  179,
      908,  887,  260,  885,  885,  887,  892,  315,  323,  329,
      328,  334,  336,  342,  343,  361,  363,  366,  364,  371,
      372,  888,  882,  886,  893,  878,  889,  884,  884,  875,
      874,  874,  887,  990,  990,  871,  877,  877,  876,  867,

      883,  867,  881,  870,  879,  866,  871,  859,  869,  858,
      862,  870,  873,  868,  868,  374,  392,  394,  400,  401,
      402,  403,  411,  421,  428,  431,  436,  442,  857,  112,
      856,  855,  854,  853,  857,  856,  845,  858,  990,  875,
      860,  839,  203,  872,  849,  837,  834,  868,  849,  838,
      838,  848,  841,  831,  990,  841,  829,  826,  990,  826,
      449,  450,  456,  457,  464,  471,  477,  478,  479,  484,
      857,  836,  990,  855,  840,  837,  990,  836,  818,  990,
      823,  821,  817,  821,  817,  812,  817,  808,  810,  827,
      824,  806,  811,  820,  822,  807,  816,  990,  801,  810,

      990,  485,  503,  506,  511,  512,  514,  517,  798,  799,
      805,  795,  794,  826,  787,  791,  804,  822,  821,  207,
      798,  805,  800,  990,  802,  795,  797,  797,  791,  779,
      784,  784,  795,  780,  520,  531,  538,  769,  778,  778,
      786,  781,  786,  990,  779,  800,  517,  259,  767,  780,
      779,  770,  795,  772,  779,  761,  769,  757,  771,  756,
      769,  761,  758,  545,  551,  560,  755,  749,  754,  764,
      745,  751,  764,  746,  749,  753,  747,  755,  744,  269,
      738,  754,  737,  750,  738,  741,  738,  190,  731,  741,
      730,  990,  734,  760,  990,  553,  740,  740,  728,  720,

      990,  737,  728,  728,  734,  724,  723,  716,  721,  730,
      714,  727,  728,  715,  990,  990,  711,  719,  720,  714,
      990,  716,  709,  990,  703,  706,  558,  706,  733,  700,
      706,  730,  703,  728,  708,  698,  703,  702,  691,  708,
      688,  704,  691,  691,  699,  683,  697,  692,  685,  685,
      679,  679,  566,  678,  683,  990,  689,  677,  677,  675,
      685,  668,  668,  684,  677,  673,  681,  668,  668,  677,
      677,  654,  990,  659,  663,  990,  990,  671,  568,  662,
      665,  669,  654,  657,  652,  651,  654,  666,  990,  652,
      678,  649,  649,  658,  652,  645,  672,  638,  638,  653,

      634,  652,  646,  647,  664,  645,  644,  645,  629,  639,
      641,  630,  639,  633,  621,  626,  287,  620,  990,  623,
      625,  618,  630,  631,  622,  629,  617,  625,  604,  990,
      623,  623,  617,  605,  615,  619,  607,  603,  990,  606,
      618,  617,  990,  602,  602,  600,  611,  600,  625,  595,
      601,  589,  599,  592,  597,  591,  589,  599,  990,  582,
      574,  564,  564,  572,  571,  555,  554,  552,  561,  554,
      553,  545,  560,  542,  552,  550,  553,  532,  545,  990,
      514,  519,  516,  512,  498,  496,  490,  498,  484,  472,
      462,  476,  467,  463,  465,  450,  455,  990,  439,  439,

      424,  990,  420,  412,  408,  416,  404,  398,  412,  390,
      990,  392,  392,  385,  990,  384,  387,  990,  378,  990,
      368,  371,  361,  350,  346,  366,  322,  325,  325,  317,
      318,  306,  279,  301,  278,  990,  263,  248,  241,  244,
      222,  990,  231,  219,  184,  990,  183,  990,  182,  186,
      138,  990,  990,  990,  132,   94,   92,   86,   30,  990,
      990,  990,  600,  606,   46,  608,  612,  616
    } ;

static const flex_int16_t yy_def[669] =
    {   0,
      662,    1,  663,  663,  663,  663,  663,  663,  663,  663,
      663,  663,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  664,  662,  662,  662,  665,  666,  666,  662,  662,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  664,  668,  662,  666,  666,  667,  662,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  668,  668,  666,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  667,  667,  667,  667,  667,  667,  667,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  667,  667,  667,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  667,  667,  667,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  667,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  667,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  667,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  667,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,    0,  662,  662,  662,  662,  662,  662
    } ;

static const flex_int16_t yy_nxt[1039] =
    {   0,
       14,   15,   16,   14,   17,   18,   19,   14,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   14,
       31,   32,   32,   33,   32,   34,   32,   32,   35,   32,
       32,   36,   32,   37,   38,   39,   32,   32,   40,   41,
       32,   32,   32,   32,   32,   32,   42,   43,   46,   88,
       68,   64,   68,   89,   69,  102,   69,  661,  105,   47,
       98,   48,   49,   50,   51,   52,   68,   53,   68,  103,
      106,   54,   55,   56,   57,   71,   58,   99,   59,   60,
       61,   62,   72,  116,   68,   68,  151,   73,   69,   69,
       68,   68,   68,   68,   69,   69,   69,   69,  161,  116,

       68,   68,   76,  162,  114,   74,   68,   68,   68,   68,
       68,  115,   78,  660,   69,   75,   77,   80,  272,   79,
       68,   68,   81,  152,   69,   69,   68,   82,   91,   83,
       68,  659,   92,  658,   69,  107,   68,   68,   93,   68,
       95,   84,   86,   69,   85,   96,   68,   97,   94,  108,
      273,  139,  109,   68,   87,   68,   68,   69,  140,   68,
       69,   68,   68,   69,   68,   69,   69,  657,   69,   68,
      155,  116,   68,  656,  119,   68,  120,   68,   68,  156,
       68,   68,   68,  121,   68,   69,   69,  116,   69,   68,
       68,  122,  123,   69,   69,   68,  420,   68,   68,   69,

       68,  206,  207,  116,  125,   68,   68,  127,   68,  285,
      655,   68,   69,   68,   68,  124,  126,   69,   69,  116,
      654,  653,  652,   68,   68,  128,  129,   69,  421,   68,
       68,  286,  130,   68,   68,  132,   68,   69,   69,   68,
       69,  349,   68,  651,  350,  133,   69,   68,  131,   68,
       68,   69,   68,   68,  650,  649,   68,   69,   68,  134,
       69,   68,  198,   68,  168,   69,  199,  169,  648,   68,
      135,   68,   68,  170,  647,   69,   68,   68,  172,   68,
       69,   68,  171,   69,  210,   69,  646,   68,  211,   68,
      173,  379,   68,   69,  380,   68,  645,   68,   68,  174,

      176,  644,   69,  411,   68,   68,  412,  643,   69,  537,
      175,   68,   68,  538,   68,   69,   69,   68,   68,  177,
       68,   69,   69,  642,  179,  178,   68,   68,   68,  180,
       69,   68,   68,   68,   68,   69,   69,   68,  181,   68,
      641,   69,   68,   69,  640,   68,   68,   68,   68,   69,
       69,  639,  219,   68,  216,   68,  217,  218,  638,  637,
      636,   68,   68,  223,   68,  220,   68,   68,   69,   68,
       69,   69,  635,   69,   68,   68,  221,   68,   69,   69,
       68,   69,   68,   68,  634,   68,  222,  633,  226,  632,
       68,   68,  227,   68,  631,   68,  630,   68,  224,   69,

      225,   69,  228,   68,   68,   68,   68,   69,   69,   69,
       69,   68,  629,   68,   68,  628,  261,  627,   69,   68,
       68,   68,   68,  626,   68,  625,  624,  262,   69,  623,
       68,   68,  263,  264,   68,   69,  622,  621,   69,   68,
       68,  266,  620,   69,  619,   68,  618,   68,  265,   69,
       68,  617,   68,   68,  616,   68,   69,   69,  269,   68,
       68,   68,  615,   69,   69,  268,  270,   68,   68,   68,
      267,   69,  614,  613,   68,   68,   68,  302,   69,  612,
       68,   68,   68,   68,   69,   69,   69,   68,   68,  611,
       68,   69,   69,  610,  609,  608,   68,   68,   68,  307,

      607,  606,  304,   68,   68,  305,   68,  605,  303,   68,
       69,  306,  604,   69,   68,   68,  308,   68,   69,   69,
       68,   69,   68,   68,   69,   68,  603,   69,  602,  601,
       68,   68,  600,   68,   68,  336,   68,  375,   69,   68,
      599,   68,  376,  598,  364,   69,  597,  596,   68,  335,
       68,  377,   69,  337,   68,  378,   68,   68,   69,  365,
       69,   68,  366,   68,   68,   69,  397,   69,  595,   68,
       68,   68,   68,   69,  594,   69,  593,   68,  592,   68,
      591,  427,  590,  589,  588,   68,  587,   68,  586,  585,
      396,  584,  453,  583,  582,  581,  580,  579,  578,  479,

       44,   44,   44,   44,   44,   44,   63,  577,   63,   63,
       63,   63,   66,   66,   70,   70,   70,   70,  117,  576,
      117,  117,  575,  574,  573,  572,  571,  570,  569,  568,
      567,  566,  565,  564,  563,  562,  561,  560,  559,  558,
      557,  556,  555,  554,  553,  552,  551,  550,  549,  548,
      547,  546,  545,  544,  543,  542,  541,  540,  539,  536,
      535,  534,  533,  532,  531,  530,  529,  528,  527,  526,
      525,  524,  523,  522,  521,  520,  519,  518,  517,  516,
      515,  514,  513,  512,  511,  510,  509,  508,  507,  506,
      505,  504,  503,  502,  501,  500,  499,  498,  497,  496,

      495,  494,  493,  492,  491,  490,  489,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,  430,  429,  428,  426,  425,  424,  423,
      422,  419,  418,  417,  416,  415,  414,  413,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  395,  394,  393,  392,  391,  390,  389,  388,  387,

      386,  385,  384,  383,  382,  381,  374,  373,  372,  371,
      370,  369,  368,  367,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      271,  260,  259,  258,  257,  256,  255,  254,  253,  252,

      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  215,  214,  213,  212,  209,  208,  205,
      204,  203,  202,  201,  200,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  167,  166,  165,  164,  163,  160,  159,  158,  157,
      154,  153,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  138,  137,  136,  118,  113,  112,  111,  110,
      104,  101,  100,   90,   45,   67,   65,   45,  662,   13,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662
    } ;

static const flex_int16_t yy_chk[1039] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   21,   47,
       32,  665,   31,   47,   32,   54,   31,  659,   56,   21,
       51,   21,   21,   21,   21,   21,   32,   21,   31,   54,
       56,   21,   21,   21,   21,   31,   21,   51,   21,   21,
       21,   21,   31,   64,   33,   34,  102,   31,   33,   34,
       35,   37,   36,   38,   35,   37,   36,   38,  110,   64,

       33,   34,   34,  110,   62,   33,   35,   37,   36,   38,
       39,   62,   35,  658,   39,   33,   34,   36,  230,   35,
       41,   40,   37,  102,   41,   40,   39,   38,   49,   38,
       68,  657,   49,  656,   68,   57,   41,   40,   49,   70,
       50,   39,   40,   70,   39,   50,   68,   50,   49,   57,
      230,   91,   57,   71,   41,   70,   72,   71,   91,   73,
       72,   74,   75,   73,   76,   74,   75,  655,   76,   71,
      105,  116,   72,  651,   71,   73,   72,   74,   75,  105,
       76,   77,   78,   74,   79,   77,   78,  116,   79,   80,
       81,   75,   76,   80,   81,   82,  388,   77,   78,   82,

       79,  160,  160,  117,   78,   80,   81,   80,   83,  243,
      650,   82,   83,   84,   85,   77,   79,   84,   85,  117,
      649,  647,  645,   86,   83,   80,   81,   86,  388,   84,
       85,  243,   83,   87,  119,   85,  120,   87,  119,   86,
      120,  320,  121,  644,  320,   85,  121,  123,   84,   87,
      119,  123,  120,  125,  643,  641,  122,  125,  121,   86,
      122,  124,  153,  123,  119,  124,  153,  121,  640,  125,
       87,  126,  122,  122,  639,  126,  127,  124,  124,  128,
      127,  129,  123,  128,  163,  129,  638,  126,  163,  131,
      124,  348,  127,  131,  348,  128,  637,  129,  130,  126,

      128,  635,  130,  380,  132,  131,  380,  634,  132,  517,
      127,  133,  134,  517,  130,  133,  134,  135,  168,  130,
      132,  135,  168,  633,  132,  131,  169,  133,  134,  133,
      169,  171,  170,  135,  168,  171,  170,  172,  135,  173,
      632,  172,  169,  173,  631,  174,  175,  171,  170,  174,
      175,  630,  171,  172,  168,  173,  169,  170,  629,  628,
      627,  174,  175,  175,  176,  172,  177,  179,  176,  178,
      177,  179,  626,  178,  180,  181,  173,  216,  180,  181,
      176,  216,  177,  179,  625,  178,  174,  624,  178,  623,
      180,  181,  179,  216,  622,  217,  621,  218,  176,  217,

      177,  218,  180,  219,  220,  221,  222,  219,  220,  221,
      222,  217,  619,  218,  223,  617,  217,  616,  223,  219,
      220,  221,  222,  614,  224,  613,  612,  218,  224,  610,
      223,  225,  220,  221,  226,  225,  609,  608,  226,  227,
      224,  224,  607,  227,  606,  228,  605,  225,  223,  228,
      226,  604,  261,  262,  603,  227,  261,  262,  227,  263,
      264,  228,  601,  263,  264,  226,  228,  265,  261,  262,
      225,  265,  600,  599,  266,  263,  264,  264,  266,  597,
      267,  268,  269,  265,  267,  268,  269,  270,  302,  596,
      266,  270,  302,  595,  594,  593,  267,  268,  269,  269,

      592,  591,  266,  270,  302,  267,  303,  590,  265,  304,
      303,  268,  589,  304,  305,  306,  270,  307,  305,  306,
      308,  307,  303,  335,  308,  304,  588,  335,  587,  586,
      305,  306,  585,  307,  336,  306,  308,  347,  336,  335,
      584,  337,  347,  583,  335,  337,  582,  581,  364,  305,
      336,  347,  364,  307,  365,  347,  396,  337,  365,  336,
      396,  427,  337,  366,  364,  427,  366,  366,  579,  453,
      365,  479,  396,  453,  578,  479,  577,  427,  576,  366,
      575,  396,  574,  573,  572,  453,  571,  479,  570,  569,
      365,  568,  427,  567,  566,  565,  564,  563,  562,  453,

      663,  663,  663,  663,  663,  663,  664,  561,  664,  664,
      664,  664,  666,  666,  667,  667,  667,  667,  668,  560,
      668,  668,  558,  557,  556,  555,  554,  553,  552,  551,
      550,  549,  548,  547,  546,  545,  544,  542,  541,  540,
      538,  537,  536,  535,  534,  533,  532,  531,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  518,  516,
      515,  514,  513,  512,  511,  510,  509,  508,  507,  506,
      505,  504,  503,  502,  501,  500,  499,  498,  497,  496,
      495,  494,  493,  492,  491,  490,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  478,  475,  474,  472,  471,

      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  455,  454,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  426,  425,  423,  422,  420,  419,  418,  417,  414,
      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  400,  399,  398,  397,  394,  393,  391,  390,
      389,  387,  386,  385,  384,  383,  382,  381,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  363,  362,  361,  360,  359,  358,  357,  356,  355,

      354,  353,  352,  351,  350,  349,  346,  345,  343,  342,
      341,  340,  339,  338,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  323,  322,  321,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  300,  299,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  279,  278,  276,
      275,  274,  272,  271,  260,  258,  257,  256,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  242,
      241,  240,  238,  237,  236,  235,  234,  233,  232,  231,
      229,  215,  214,  213,  212,  211,  210,  209,  208,  207,

      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  167,  166,  165,  164,  162,  161,  159,
      158,  157,  156,  155,  154,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  138,  137,
      136,  115,  114,  113,  112,  111,  109,  108,  107,  106,
      104,  103,  101,  100,   99,   98,   97,   96,   95,   94,
       93,   92,   90,   89,   88,   67,   61,   60,   59,   58,
       55,   53,   52,   48,   45,   27,   26,   20,   13,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,

      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "epddl.l"
/* -*- c++ -*- File generated by the BNF Converter (bnfc 2.9.4). */
/* Lexer definition for use with FLex */
#define YY_NO_INPUT 1
#line 9 "epddl.l"
#include "Absyn.H"
#include "Bison.H"

#define initialize_lexer epddl__initialize_lexer

static void update_loc(YYLTYPE* loc, char* text)
{
  loc->first_line = loc->last_line;
  loc->first_column = loc->last_column;
  int i = 0;
  for (; text[i] != '\0'; ++i) {
      if (text[i] == '\n') {
          ++loc->last_line;
          loc->last_column = 0;
      } else {
          ++loc->last_column;
      }
  }
}
#define YY_USER_ACTION update_loc(yylloc, yytext);

#line 1126 "Lexer.C"

#line 1128 "Lexer.C"

#define INITIAL 0
#define CHAR 1
#define CHARESC 2
#define CHAREND 3
#define STRING 4
#define ESCAPED 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 39 "epddl.l"


#line 1418 "Lexer.C"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 663 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 990 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "epddl.l"
return _LPAREN;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "epddl.l"
return _RPAREN;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "epddl.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "epddl.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "epddl.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "epddl.l"
return _SYMB_5;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "epddl.l"
return _SYMB_6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "epddl.l"
return _SYMB_7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "epddl.l"
return _SYMB_8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "epddl.l"
return _SYMB_9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "epddl.l"
return _SYMB_10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "epddl.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "epddl.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "epddl.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "epddl.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "epddl.l"
return _SYMB_15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "epddl.l"
return _SYMB_16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "epddl.l"
return _SYMB_17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "epddl.l"
return _SYMB_18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "epddl.l"
return _SYMB_19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "epddl.l"
return _SYMB_20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "epddl.l"
return _SYMB_21;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "epddl.l"
return _SYMB_22;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "epddl.l"
return _LBRACE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "epddl.l"
return _RBRACE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "epddl.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "epddl.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "epddl.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "epddl.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "epddl.l"
return _LBRACK;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "epddl.l"
return _RBRACK;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "epddl.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "epddl.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "epddl.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "epddl.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "epddl.l"
return _EQ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "epddl.l"
return _LT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "epddl.l"
return _GT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "epddl.l"
return _MINUS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "epddl.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "epddl.l"
return _DCOLON;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "epddl.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "epddl.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "epddl.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "epddl.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "epddl.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "epddl.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "epddl.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "epddl.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "epddl.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "epddl.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "epddl.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "epddl.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "epddl.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "epddl.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "epddl.l"
return _SYMB_55;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "epddl.l"
return _SYMB_56;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "epddl.l"
return _SYMB_57;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "epddl.l"
return _SYMB_58;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "epddl.l"
return _SYMB_59;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "epddl.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "epddl.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "epddl.l"
return _SYMB_62;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "epddl.l"
return _KW_All;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "epddl.l"
return _KW_agent;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "epddl.l"
return _KW_and;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "epddl.l"
return _KW_as;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "epddl.l"
return _KW_define;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "epddl.l"
return _KW_domain;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "epddl.l"
return _KW_false;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 111 "epddl.l"
return _KW_forall;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 112 "epddl.l"
return _KW_formula;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 113 "epddl.l"
return _KW_if;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 114 "epddl.l"
return _KW_iff;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 115 "epddl.l"
return _KW_imply;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 116 "epddl.l"
return _KW_library;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 117 "epddl.l"
return _KW_literal;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 118 "epddl.l"
return _KW_not;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 119 "epddl.l"
return _KW_or;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "epddl.l"
return _KW_otherwise;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 121 "epddl.l"
return _KW_postcondition;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 122 "epddl.l"
return _KW_predicate;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 123 "epddl.l"
return _KW_problem;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 124 "epddl.l"
return _KW_set;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 125 "epddl.l"
return _KW_true;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 127 "epddl.l"
/* skip */; /* BNFC: comment ";" */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 129 "epddl.l"
yylval->_string = strdup(yytext); return T_Name;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 130 "epddl.l"
yylval->_string = strdup(yytext); return T_AgentName;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 131 "epddl.l"
yylval->_string = strdup(yytext); return T_ModalityName;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 132 "epddl.l"
yylval->_string = strdup(yytext); return T_Variable;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 133 "epddl.l"
yylval->_int = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 134 "epddl.l"
/* ignore white space. */;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 135 "epddl.l"
return _ERROR_;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "epddl.l"
ECHO;
	YY_BREAK
#line 1946 "Lexer.C"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 663 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 663 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 662);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 137 "epddl.l"


yyscan_t initialize_lexer(FILE *inp)
{
  yyscan_t scanner;
  if (yylex_init_extra(NULL, &scanner)) return 0;
  if (inp) yyrestart(inp, scanner);
  return scanner;
}


