/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitMainDef(MainDef *t) {} //abstract class
void Skeleton::visitDomainDef(DomainDef *t) {} //abstract class
void Skeleton::visitDomainItemDef(DomainItemDef *t) {} //abstract class
void Skeleton::visitDomainLibrariesNameDef(DomainLibrariesNameDef *t) {} //abstract class
void Skeleton::visitRequireDef(RequireDef *t) {} //abstract class
void Skeleton::visitTypesDef(TypesDef *t) {} //abstract class
void Skeleton::visitPredicateListDef(PredicateListDef *t) {} //abstract class
void Skeleton::visitPredicateDef(PredicateDef *t) {} //abstract class
void Skeleton::visitModalitiesDef(ModalitiesDef *t) {} //abstract class
void Skeleton::visitObservabilityGroupsDef(ObservabilityGroupsDef *t) {} //abstract class
void Skeleton::visitActionDef(ActionDef *t) {} //abstract class
void Skeleton::visitActionParameterDef(ActionParameterDef *t) {} //abstract class
void Skeleton::visitActionConditionsDef(ActionConditionsDef *t) {} //abstract class
void Skeleton::visitActionTypeSignatureDef(ActionTypeSignatureDef *t) {} //abstract class
void Skeleton::visitActionPreDef(ActionPreDef *t) {} //abstract class
void Skeleton::visitActionObsDef(ActionObsDef *t) {} //abstract class
void Skeleton::visitObsConditionDef(ObsConditionDef *t) {} //abstract class
void Skeleton::visitLibraryDef(LibraryDef *t) {} //abstract class
void Skeleton::visitLibraryItemDef(LibraryItemDef *t) {} //abstract class
void Skeleton::visitActionTypeDef(ActionTypeDef *t) {} //abstract class
void Skeleton::visitActionTypeParameterDef(ActionTypeParameterDef *t) {} //abstract class
void Skeleton::visitActionTypeFrameDef(ActionTypeFrameDef *t) {} //abstract class
void Skeleton::visitActionTypeEventsDef(ActionTypeEventsDef *t) {} //abstract class
void Skeleton::visitActionTypeRelDef(ActionTypeRelDef *t) {} //abstract class
void Skeleton::visitActionTypeDesDef(ActionTypeDesDef *t) {} //abstract class
void Skeleton::visitEventSignature(EventSignature *t) {} //abstract class
void Skeleton::visitActionRelations(ActionRelations *t) {} //abstract class
void Skeleton::visitEventRelation(EventRelation *t) {} //abstract class
void Skeleton::visitEventNamePair(EventNamePair *t) {} //abstract class
void Skeleton::visitEventDef(EventDef *t) {} //abstract class
void Skeleton::visitEventParameterDef(EventParameterDef *t) {} //abstract class
void Skeleton::visitEventPreDef(EventPreDef *t) {} //abstract class
void Skeleton::visitEventPostDef(EventPostDef *t) {} //abstract class
void Skeleton::visitEventPostconditions(EventPostconditions *t) {} //abstract class
void Skeleton::visitPostcondition(Postcondition *t) {} //abstract class
void Skeleton::visitLiteralPostcondition(LiteralPostcondition *t) {} //abstract class
void Skeleton::visitProblemDef(ProblemDef *t) {} //abstract class
void Skeleton::visitProblemItemDef(ProblemItemDef *t) {} //abstract class
void Skeleton::visitProblemDomainNameDef(ProblemDomainNameDef *t) {} //abstract class
void Skeleton::visitAgentNamesDef(AgentNamesDef *t) {} //abstract class
void Skeleton::visitAgentGroupsListDef(AgentGroupsListDef *t) {} //abstract class
void Skeleton::visitAgentGroupDef(AgentGroupDef *t) {} //abstract class
void Skeleton::visitObjectNamesDef(ObjectNamesDef *t) {} //abstract class
void Skeleton::visitFactListDef(FactListDef *t) {} //abstract class
void Skeleton::visitFactDef(FactDef *t) {} //abstract class
void Skeleton::visitInitDef(InitDef *t) {} //abstract class
void Skeleton::visitInitialStateDescr(InitialStateDescr *t) {} //abstract class
void Skeleton::visitFTheoryFormula(FTheoryFormula *t) {} //abstract class
void Skeleton::visitKPredicateFormula(KPredicateFormula *t) {} //abstract class
void Skeleton::visitKWPredicateFormula(KWPredicateFormula *t) {} //abstract class
void Skeleton::visitNotKWPredicateFormula(NotKWPredicateFormula *t) {} //abstract class
void Skeleton::visitInitialModelDef(InitialModelDef *t) {} //abstract class
void Skeleton::visitModelWorldsDef(ModelWorldsDef *t) {} //abstract class
void Skeleton::visitModelRelDef(ModelRelDef *t) {} //abstract class
void Skeleton::visitModelValDef(ModelValDef *t) {} //abstract class
void Skeleton::visitModelDesDef(ModelDesDef *t) {} //abstract class
void Skeleton::visitModelRelations(ModelRelations *t) {} //abstract class
void Skeleton::visitModelValuation(ModelValuation *t) {} //abstract class
void Skeleton::visitWorldRelation(WorldRelation *t) {} //abstract class
void Skeleton::visitWorldNamePair(WorldNamePair *t) {} //abstract class
void Skeleton::visitWorldValuation(WorldValuation *t) {} //abstract class
void Skeleton::visitGoalDef(GoalDef *t) {} //abstract class
void Skeleton::visitFormula(Formula *t) {} //abstract class
void Skeleton::visitAtomicFormula(AtomicFormula *t) {} //abstract class
void Skeleton::visitAtomicEqFormula(AtomicEqFormula *t) {} //abstract class
void Skeleton::visitFormulaOrEmpty(FormulaOrEmpty *t) {} //abstract class
void Skeleton::visitMetaTerm(MetaTerm *t) {} //abstract class
void Skeleton::visitTerm(Term *t) {} //abstract class
void Skeleton::visitGroundTerm(GroundTerm *t) {} //abstract class
void Skeleton::visitModality(Modality *t) {} //abstract class
void Skeleton::visitSingleModality(SingleModality *t) {} //abstract class
void Skeleton::visitGroupModality(GroupModality *t) {} //abstract class
void Skeleton::visitModalityLabel(ModalityLabel *t) {} //abstract class
void Skeleton::visitKnowsWhether(KnowsWhether *t) {} //abstract class
void Skeleton::visitLiteral(Literal *t) {} //abstract class
void Skeleton::visitConditionFormula(ConditionFormula *t) {} //abstract class
void Skeleton::visitCondition(Condition *t) {} //abstract class
void Skeleton::visitAtomicCondition(AtomicCondition *t) {} //abstract class
void Skeleton::visitPredicateFormula(PredicateFormula *t) {} //abstract class
void Skeleton::visitGenericName(GenericName *t) {} //abstract class
void Skeleton::visitTypedIdentList(TypedIdentList *t) {} //abstract class
void Skeleton::visitTypedVariableList(TypedVariableList *t) {} //abstract class
void Skeleton::visitPredicateName(PredicateName *t) {} //abstract class
void Skeleton::visitModalityAgent(ModalityAgent *t) {} //abstract class
void Skeleton::visitModalityAgentGroup(ModalityAgentGroup *t) {} //abstract class
void Skeleton::visitAgentGroupName(AgentGroupName *t) {} //abstract class
void Skeleton::visitObservingAgentGroup(ObservingAgentGroup *t) {} //abstract class
void Skeleton::visitObservingAgent(ObservingAgent *t) {} //abstract class
void Skeleton::visitAgentGroup(AgentGroup *t) {} //abstract class
void Skeleton::visitAllAgents(AllAgents *t) {} //abstract class
void Skeleton::visitAnonVarAgent(AnonVarAgent *t) {} //abstract class
void Skeleton::visitParameter(Parameter *t) {} //abstract class
void Skeleton::visitParameterValue(ParameterValue *t) {} //abstract class
void Skeleton::visitPostParameterValue(PostParameterValue *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitReservedType(ReservedType *t) {} //abstract class
void Skeleton::visitDomainName(DomainName *t) {} //abstract class
void Skeleton::visitLibraryName(LibraryName *t) {} //abstract class
void Skeleton::visitProblemName(ProblemName *t) {} //abstract class
void Skeleton::visitActionName(ActionName *t) {} //abstract class
void Skeleton::visitActionTypeName(ActionTypeName *t) {} //abstract class
void Skeleton::visitEventName(EventName *t) {} //abstract class
void Skeleton::visitModelName(ModelName *t) {} //abstract class
void Skeleton::visitWorldName(WorldName *t) {} //abstract class
void Skeleton::visitRequireKey(RequireKey *t) {} //abstract class
void Skeleton::visitTrivialDef(TrivialDef *t) {} //abstract class

void Skeleton::visitName(Name *name)
{
  /* Code For Name Goes Here */

  visitString(name->string_);
  visitInteger(name->integer_);

}

void Skeleton::visitAgentName(AgentName *agent_name)
{
  /* Code For AgentName Goes Here */

  visitString(agent_name->string_);
  visitInteger(agent_name->integer_);

}

void Skeleton::visitModalityName(ModalityName *modality_name)
{
  /* Code For ModalityName Goes Here */

  visitString(modality_name->string_);
  visitInteger(modality_name->integer_);

}

void Skeleton::visitVariable(Variable *variable)
{
  /* Code For Variable Goes Here */

  visitString(variable->string_);
  visitInteger(variable->integer_);

}

void Skeleton::visitDomain(Domain *domain)
{
  /* Code For Domain Goes Here */

  if (domain->domaindef_) domain->domaindef_->accept(this);

}

void Skeleton::visitActionTypeLibrary(ActionTypeLibrary *action_type_library)
{
  /* Code For ActionTypeLibrary Goes Here */

  if (action_type_library->librarydef_) action_type_library->librarydef_->accept(this);

}

void Skeleton::visitProblem(Problem *problem)
{
  /* Code For Problem Goes Here */

  if (problem->problemdef_) problem->problemdef_->accept(this);

}

void Skeleton::visitEPDDLDomain(EPDDLDomain *epddl_domain)
{
  /* Code For EPDDLDomain Goes Here */

  if (epddl_domain->domainname_) epddl_domain->domainname_->accept(this);
  if (epddl_domain->listdomainitemdef_) epddl_domain->listdomainitemdef_->accept(this);

}

void Skeleton::visitEPDDLDomLibrary(EPDDLDomLibrary *epddl_dom_library)
{
  /* Code For EPDDLDomLibrary Goes Here */

  if (epddl_dom_library->domainlibrariesnamedef_) epddl_dom_library->domainlibrariesnamedef_->accept(this);

}

void Skeleton::visitEPDDLDomRequire(EPDDLDomRequire *epddl_dom_require)
{
  /* Code For EPDDLDomRequire Goes Here */

  if (epddl_dom_require->requiredef_) epddl_dom_require->requiredef_->accept(this);

}

void Skeleton::visitEPDDLDomTypes(EPDDLDomTypes *epddl_dom_types)
{
  /* Code For EPDDLDomTypes Goes Here */

  if (epddl_dom_types->typesdef_) epddl_dom_types->typesdef_->accept(this);

}

void Skeleton::visitEPDDLDomPredicates(EPDDLDomPredicates *epddl_dom_predicates)
{
  /* Code For EPDDLDomPredicates Goes Here */

  if (epddl_dom_predicates->predicatelistdef_) epddl_dom_predicates->predicatelistdef_->accept(this);

}

void Skeleton::visitEPDDLDomModalities(EPDDLDomModalities *epddl_dom_modalities)
{
  /* Code For EPDDLDomModalities Goes Here */

  if (epddl_dom_modalities->modalitiesdef_) epddl_dom_modalities->modalitiesdef_->accept(this);

}

void Skeleton::visitEPDDLDomObsGroups(EPDDLDomObsGroups *epddl_dom_obs_groups)
{
  /* Code For EPDDLDomObsGroups Goes Here */

  if (epddl_dom_obs_groups->observabilitygroupsdef_) epddl_dom_obs_groups->observabilitygroupsdef_->accept(this);

}

void Skeleton::visitEPDDLDomAction(EPDDLDomAction *epddl_dom_action)
{
  /* Code For EPDDLDomAction Goes Here */

  if (epddl_dom_action->actiondef_) epddl_dom_action->actiondef_->accept(this);

}

void Skeleton::visitEPDDLDomLibraryNames(EPDDLDomLibraryNames *epddl_dom_library_names)
{
  /* Code For EPDDLDomLibraryNames Goes Here */

  if (epddl_dom_library_names->listlibraryname_) epddl_dom_library_names->listlibraryname_->accept(this);

}

void Skeleton::visitEPDDLRequire(EPDDLRequire *epddl_require)
{
  /* Code For EPDDLRequire Goes Here */

  if (epddl_require->listrequirekey_) epddl_require->listrequirekey_->accept(this);

}

void Skeleton::visitEPDDLTypes(EPDDLTypes *epddl_types)
{
  /* Code For EPDDLTypes Goes Here */

  if (epddl_types->typedidentlist_) epddl_types->typedidentlist_->accept(this);

}

void Skeleton::visitEPDDLPredicateList(EPDDLPredicateList *epddl_predicate_list)
{
  /* Code For EPDDLPredicateList Goes Here */

  if (epddl_predicate_list->listpredicatedef_) epddl_predicate_list->listpredicatedef_->accept(this);

}

void Skeleton::visitEPDDLPredicateDef(EPDDLPredicateDef *epddl_predicate_def)
{
  /* Code For EPDDLPredicateDef Goes Here */

  if (epddl_predicate_def->predicatename_) epddl_predicate_def->predicatename_->accept(this);
  if (epddl_predicate_def->typedvariablelist_) epddl_predicate_def->typedvariablelist_->accept(this);

}

void Skeleton::visitEPDDLModalities(EPDDLModalities *epddl_modalities)
{
  /* Code For EPDDLModalities Goes Here */

  if (epddl_modalities->listmodalityname_) epddl_modalities->listmodalityname_->accept(this);

}

void Skeleton::visitEPDDLObsGroupsNames(EPDDLObsGroupsNames *epddl_obs_groups_names)
{
  /* Code For EPDDLObsGroupsNames Goes Here */

  if (epddl_obs_groups_names->listobservingagentgroup_) epddl_obs_groups_names->listobservingagentgroup_->accept(this);

}

void Skeleton::visitEPDDLAction(EPDDLAction *epddl_action)
{
  /* Code For EPDDLAction Goes Here */

  if (epddl_action->actionname_) epddl_action->actionname_->accept(this);
  if (epddl_action->actionparameterdef_) epddl_action->actionparameterdef_->accept(this);
  if (epddl_action->actionconditionsdef_) epddl_action->actionconditionsdef_->accept(this);
  if (epddl_action->actiontypesignaturedef_) epddl_action->actiontypesignaturedef_->accept(this);
  if (epddl_action->actionpredef_) epddl_action->actionpredef_->accept(this);
  if (epddl_action->actionobsdef_) epddl_action->actionobsdef_->accept(this);

}

void Skeleton::visitActionParam(ActionParam *action_param)
{
  /* Code For ActionParam Goes Here */

  if (action_param->typedvariablelist_) action_param->typedvariablelist_->accept(this);

}

void Skeleton::visitActionCond(ActionCond *action_cond)
{
  /* Code For ActionCond Goes Here */

  if (action_cond->conditionformula_) action_cond->conditionformula_->accept(this);

}

void Skeleton::visitEmptyActionCond(EmptyActionCond *empty_action_cond)
{
  /* Code For EmptyActionCond Goes Here */


}

void Skeleton::visitActionSignature(ActionSignature *action_signature)
{
  /* Code For ActionSignature Goes Here */

  if (action_signature->actiontypename_) action_signature->actiontypename_->accept(this);
  if (action_signature->listparameter_) action_signature->listparameter_->accept(this);

}

void Skeleton::visitActionPre(ActionPre *action_pre)
{
  /* Code For ActionPre Goes Here */

  if (action_pre->formulaorempty_) action_pre->formulaorempty_->accept(this);

}

void Skeleton::visitActionObs(ActionObs *action_obs)
{
  /* Code For ActionObs Goes Here */

  if (action_obs->listobsconditiondef_) action_obs->listobsconditiondef_->accept(this);

}

void Skeleton::visitEmptyActionObs(EmptyActionObs *empty_action_obs)
{
  /* Code For EmptyActionObs Goes Here */


}

void Skeleton::visitEmptyObsCond(EmptyObsCond *empty_obs_cond)
{
  /* Code For EmptyObsCond Goes Here */

  if (empty_obs_cond->observingagent_) empty_obs_cond->observingagent_->accept(this);
  if (empty_obs_cond->observingagentgroup_) empty_obs_cond->observingagentgroup_->accept(this);

}

void Skeleton::visitObsCond(ObsCond *obs_cond)
{
  /* Code For ObsCond Goes Here */

  if (obs_cond->observingagent_) obs_cond->observingagent_->accept(this);
  if (obs_cond->observingagentgroup_) obs_cond->observingagentgroup_->accept(this);
  if (obs_cond->formula_) obs_cond->formula_->accept(this);

}

void Skeleton::visitObsOtherwiseCond(ObsOtherwiseCond *obs_otherwise_cond)
{
  /* Code For ObsOtherwiseCond Goes Here */

  if (obs_otherwise_cond->observingagent_) obs_otherwise_cond->observingagent_->accept(this);
  if (obs_otherwise_cond->observingagentgroup_) obs_otherwise_cond->observingagentgroup_->accept(this);

}

void Skeleton::visitEPDDLLibrary(EPDDLLibrary *epddl_library)
{
  /* Code For EPDDLLibrary Goes Here */

  if (epddl_library->libraryname_) epddl_library->libraryname_->accept(this);
  if (epddl_library->listlibraryitemdef_) epddl_library->listlibraryitemdef_->accept(this);

}

void Skeleton::visitEPDDLLibRequire(EPDDLLibRequire *epddl_lib_require)
{
  /* Code For EPDDLLibRequire Goes Here */

  if (epddl_lib_require->requiredef_) epddl_lib_require->requiredef_->accept(this);

}

void Skeleton::visitEPDDLLibModalities(EPDDLLibModalities *epddl_lib_modalities)
{
  /* Code For EPDDLLibModalities Goes Here */

  if (epddl_lib_modalities->modalitiesdef_) epddl_lib_modalities->modalitiesdef_->accept(this);

}

void Skeleton::visitEPDDLLibObsGroups(EPDDLLibObsGroups *epddl_lib_obs_groups)
{
  /* Code For EPDDLLibObsGroups Goes Here */

  if (epddl_lib_obs_groups->observabilitygroupsdef_) epddl_lib_obs_groups->observabilitygroupsdef_->accept(this);

}

void Skeleton::visitEPDDLLibActionType(EPDDLLibActionType *epddl_lib_action_type)
{
  /* Code For EPDDLLibActionType Goes Here */

  if (epddl_lib_action_type->actiontypedef_) epddl_lib_action_type->actiontypedef_->accept(this);

}

void Skeleton::visitEPDDLLibEvent(EPDDLLibEvent *epddl_lib_event)
{
  /* Code For EPDDLLibEvent Goes Here */

  if (epddl_lib_event->eventdef_) epddl_lib_event->eventdef_->accept(this);

}

void Skeleton::visitEPDDLActType(EPDDLActType *epddl_act_type)
{
  /* Code For EPDDLActType Goes Here */

  if (epddl_act_type->actiontypename_) epddl_act_type->actiontypename_->accept(this);
  if (epddl_act_type->actiontypeparameterdef_) epddl_act_type->actiontypeparameterdef_->accept(this);
  if (epddl_act_type->actiontypeframedef_) epddl_act_type->actiontypeframedef_->accept(this);
  if (epddl_act_type->actiontypeeventsdef_) epddl_act_type->actiontypeeventsdef_->accept(this);
  if (epddl_act_type->actiontypereldef_) epddl_act_type->actiontypereldef_->accept(this);
  if (epddl_act_type->actiontypedesdef_) epddl_act_type->actiontypedesdef_->accept(this);

}

void Skeleton::visitActTypeParam(ActTypeParam *act_type_param)
{
  /* Code For ActTypeParam Goes Here */

  if (act_type_param->typedvariablelist_) act_type_param->typedvariablelist_->accept(this);

}

void Skeleton::visitActTypeFrame(ActTypeFrame *act_type_frame)
{
  /* Code For ActTypeFrame Goes Here */

  if (act_type_frame->listobservingagentgroup_) act_type_frame->listobservingagentgroup_->accept(this);

}

void Skeleton::visitEmptyActTypeFrame(EmptyActTypeFrame *empty_act_type_frame)
{
  /* Code For EmptyActTypeFrame Goes Here */


}

void Skeleton::visitActTypeEvents(ActTypeEvents *act_type_events)
{
  /* Code For ActTypeEvents Goes Here */

  if (act_type_events->listeventsignature_) act_type_events->listeventsignature_->accept(this);

}

void Skeleton::visitActTypeRel(ActTypeRel *act_type_rel)
{
  /* Code For ActTypeRel Goes Here */

  if (act_type_rel->actionrelations_) act_type_rel->actionrelations_->accept(this);

}

void Skeleton::visitActTypeDes(ActTypeDes *act_type_des)
{
  /* Code For ActTypeDes Goes Here */

  if (act_type_des->listeventname_) act_type_des->listeventname_->accept(this);

}

void Skeleton::visitEventSign(EventSign *event_sign)
{
  /* Code For EventSign Goes Here */

  if (event_sign->eventname_) event_sign->eventname_->accept(this);
  if (event_sign->listparameter_) event_sign->listparameter_->accept(this);

}

void Skeleton::visitEventsActionRel(EventsActionRel *events_action_rel)
{
  /* Code For EventsActionRel Goes Here */

  if (events_action_rel->listeventrelation_) events_action_rel->listeventrelation_->accept(this);

}

void Skeleton::visitTrivialActionRel(TrivialActionRel *trivial_action_rel)
{
  /* Code For TrivialActionRel Goes Here */

  if (trivial_action_rel->trivialdef_) trivial_action_rel->trivialdef_->accept(this);

}

void Skeleton::visitEventRel(EventRel *event_rel)
{
  /* Code For EventRel Goes Here */

  if (event_rel->agentgroup_) event_rel->agentgroup_->accept(this);
  if (event_rel->listeventnamepair_) event_rel->listeventnamepair_->accept(this);

}

void Skeleton::visitTrivialEventRel(TrivialEventRel *trivial_event_rel)
{
  /* Code For TrivialEventRel Goes Here */

  if (trivial_event_rel->agentgroup_) trivial_event_rel->agentgroup_->accept(this);
  if (trivial_event_rel->trivialdef_) trivial_event_rel->trivialdef_->accept(this);

}

void Skeleton::visitEventPair(EventPair *event_pair)
{
  /* Code For EventPair Goes Here */

  if (event_pair->eventname_1) event_pair->eventname_1->accept(this);
  if (event_pair->eventname_2) event_pair->eventname_2->accept(this);

}

void Skeleton::visitEPDDLEvent(EPDDLEvent *epddl_event)
{
  /* Code For EPDDLEvent Goes Here */

  if (epddl_event->eventname_) epddl_event->eventname_->accept(this);
  if (epddl_event->eventparameterdef_) epddl_event->eventparameterdef_->accept(this);
  if (epddl_event->eventpredef_) epddl_event->eventpredef_->accept(this);
  if (epddl_event->eventpostdef_) epddl_event->eventpostdef_->accept(this);

}

void Skeleton::visitEventParam(EventParam *event_param)
{
  /* Code For EventParam Goes Here */

  if (event_param->typedvariablelist_) event_param->typedvariablelist_->accept(this);

}

void Skeleton::visitEventPre(EventPre *event_pre)
{
  /* Code For EventPre Goes Here */

  if (event_pre->formulaorempty_) event_pre->formulaorempty_->accept(this);

}

void Skeleton::visitEventPost(EventPost *event_post)
{
  /* Code For EventPost Goes Here */

  if (event_post->eventpostconditions_) event_post->eventpostconditions_->accept(this);

}

void Skeleton::visitEmptyEventPost(EmptyEventPost *empty_event_post)
{
  /* Code For EmptyEventPost Goes Here */


}

void Skeleton::visitPostconditions(Postconditions *postconditions)
{
  /* Code For Postconditions Goes Here */

  if (postconditions->listpostcondition_) postconditions->listpostcondition_->accept(this);

}

void Skeleton::visitTrivialPostconditions(TrivialPostconditions *trivial_postconditions)
{
  /* Code For TrivialPostconditions Goes Here */

  if (trivial_postconditions->trivialdef_) trivial_postconditions->trivialdef_->accept(this);

}

void Skeleton::visitForallPostcondition(ForallPostcondition *forall_postcondition)
{
  /* Code For ForallPostcondition Goes Here */

  if (forall_postcondition->typedvariablelist_) forall_postcondition->typedvariablelist_->accept(this);
  if (forall_postcondition->listliteralpostcondition_) forall_postcondition->listliteralpostcondition_->accept(this);

}

void Skeleton::visitSinglePostcondition(SinglePostcondition *single_postcondition)
{
  /* Code For SinglePostcondition Goes Here */

  if (single_postcondition->literalpostcondition_) single_postcondition->literalpostcondition_->accept(this);

}

void Skeleton::visitVarPostcondition(VarPostcondition *var_postcondition)
{
  /* Code For VarPostcondition Goes Here */

  if (var_postcondition->variable_) var_postcondition->variable_->accept(this);

}

void Skeleton::visitLiteralPost(LiteralPost *literal_post)
{
  /* Code For LiteralPost Goes Here */

  if (literal_post->literal_) literal_post->literal_->accept(this);
  if (literal_post->formulaorempty_) literal_post->formulaorempty_->accept(this);

}

void Skeleton::visitTrivialLiteralPost(TrivialLiteralPost *trivial_literal_post)
{
  /* Code For TrivialLiteralPost Goes Here */

  if (trivial_literal_post->literal_) trivial_literal_post->literal_->accept(this);

}

void Skeleton::visitEPDDLProblem(EPDDLProblem *epddl_problem)
{
  /* Code For EPDDLProblem Goes Here */

  if (epddl_problem->problemname_) epddl_problem->problemname_->accept(this);
  if (epddl_problem->listproblemitemdef_) epddl_problem->listproblemitemdef_->accept(this);

}

void Skeleton::visitEPDDLProbDomain(EPDDLProbDomain *epddl_prob_domain)
{
  /* Code For EPDDLProbDomain Goes Here */

  if (epddl_prob_domain->problemdomainnamedef_) epddl_prob_domain->problemdomainnamedef_->accept(this);

}

void Skeleton::visitEPDDLProbRequire(EPDDLProbRequire *epddl_prob_require)
{
  /* Code For EPDDLProbRequire Goes Here */

  if (epddl_prob_require->requiredef_) epddl_prob_require->requiredef_->accept(this);

}

void Skeleton::visitEPDDLProbModalities(EPDDLProbModalities *epddl_prob_modalities)
{
  /* Code For EPDDLProbModalities Goes Here */

  if (epddl_prob_modalities->modalitiesdef_) epddl_prob_modalities->modalitiesdef_->accept(this);

}

void Skeleton::visitEPDDLProbAgents(EPDDLProbAgents *epddl_prob_agents)
{
  /* Code For EPDDLProbAgents Goes Here */

  if (epddl_prob_agents->agentnamesdef_) epddl_prob_agents->agentnamesdef_->accept(this);

}

void Skeleton::visitEPDDLProbAgentGroups(EPDDLProbAgentGroups *epddl_prob_agent_groups)
{
  /* Code For EPDDLProbAgentGroups Goes Here */

  if (epddl_prob_agent_groups->agentgroupslistdef_) epddl_prob_agent_groups->agentgroupslistdef_->accept(this);

}

void Skeleton::visitEPDDLProbObjects(EPDDLProbObjects *epddl_prob_objects)
{
  /* Code For EPDDLProbObjects Goes Here */

  if (epddl_prob_objects->objectnamesdef_) epddl_prob_objects->objectnamesdef_->accept(this);

}

void Skeleton::visitEPDDLProbFacts(EPDDLProbFacts *epddl_prob_facts)
{
  /* Code For EPDDLProbFacts Goes Here */

  if (epddl_prob_facts->factlistdef_) epddl_prob_facts->factlistdef_->accept(this);

}

void Skeleton::visitEPDDLProbInit(EPDDLProbInit *epddl_prob_init)
{
  /* Code For EPDDLProbInit Goes Here */

  if (epddl_prob_init->initdef_) epddl_prob_init->initdef_->accept(this);

}

void Skeleton::visitEPDDLProbInitModel(EPDDLProbInitModel *epddl_prob_init_model)
{
  /* Code For EPDDLProbInitModel Goes Here */

  if (epddl_prob_init_model->initialmodeldef_) epddl_prob_init_model->initialmodeldef_->accept(this);

}

void Skeleton::visitEPDDLProbGoal(EPDDLProbGoal *epddl_prob_goal)
{
  /* Code For EPDDLProbGoal Goes Here */

  if (epddl_prob_goal->goaldef_) epddl_prob_goal->goaldef_->accept(this);

}

void Skeleton::visitEPDDLProbDomainName(EPDDLProbDomainName *epddl_prob_domain_name)
{
  /* Code For EPDDLProbDomainName Goes Here */

  if (epddl_prob_domain_name->domainname_) epddl_prob_domain_name->domainname_->accept(this);

}

void Skeleton::visitEPDDLAgentNames(EPDDLAgentNames *epddl_agent_names)
{
  /* Code For EPDDLAgentNames Goes Here */

  if (epddl_agent_names->listagentname_) epddl_agent_names->listagentname_->accept(this);

}

void Skeleton::visitEPDDLAgentGroupsList(EPDDLAgentGroupsList *epddl_agent_groups_list)
{
  /* Code For EPDDLAgentGroupsList Goes Here */

  if (epddl_agent_groups_list->listagentgroupdef_) epddl_agent_groups_list->listagentgroupdef_->accept(this);

}

void Skeleton::visitEPDDLAgentGroupDef(EPDDLAgentGroupDef *epddl_agent_group_def)
{
  /* Code For EPDDLAgentGroupDef Goes Here */

  if (epddl_agent_group_def->listagentname_) epddl_agent_group_def->listagentname_->accept(this);
  if (epddl_agent_group_def->agentgroupname_) epddl_agent_group_def->agentgroupname_->accept(this);

}

void Skeleton::visitEPDDLObjectNames(EPDDLObjectNames *epddl_object_names)
{
  /* Code For EPDDLObjectNames Goes Here */

  if (epddl_object_names->typedidentlist_) epddl_object_names->typedidentlist_->accept(this);

}

void Skeleton::visitEPDDLFactList(EPDDLFactList *epddl_fact_list)
{
  /* Code For EPDDLFactList Goes Here */

  if (epddl_fact_list->listfactdef_) epddl_fact_list->listfactdef_->accept(this);

}

void Skeleton::visitEPDDLFactDef(EPDDLFactDef *epddl_fact_def)
{
  /* Code For EPDDLFactDef Goes Here */

  if (epddl_fact_def->predicatename_) epddl_fact_def->predicatename_->accept(this);
  if (epddl_fact_def->listgenericname_) epddl_fact_def->listgenericname_->accept(this);

}

void Skeleton::visitEPDDLInitialState(EPDDLInitialState *epddl_initial_state)
{
  /* Code For EPDDLInitialState Goes Here */

  if (epddl_initial_state->initialstatedescr_) epddl_initial_state->initialstatedescr_->accept(this);

}

void Skeleton::visitFinitaryTheoryDescr(FinitaryTheoryDescr *finitary_theory_descr)
{
  /* Code For FinitaryTheoryDescr Goes Here */

  if (finitary_theory_descr->listftheoryformula_) finitary_theory_descr->listftheoryformula_->accept(this);

}

void Skeleton::visitInitialModelDescr(InitialModelDescr *initial_model_descr)
{
  /* Code For InitialModelDescr Goes Here */

  if (initial_model_descr->modelname_) initial_model_descr->modelname_->accept(this);

}

void Skeleton::visitFTheoryPredForm(FTheoryPredForm *f_theory_pred_form)
{
  /* Code For FTheoryPredForm Goes Here */

  if (f_theory_pred_form->predicateformula_) f_theory_pred_form->predicateformula_->accept(this);

}

void Skeleton::visitFTheoryCKPredForm(FTheoryCKPredForm *f_theory_ck_pred_form)
{
  /* Code For FTheoryCKPredForm Goes Here */

  if (f_theory_ck_pred_form->allagents_) f_theory_ck_pred_form->allagents_->accept(this);
  if (f_theory_ck_pred_form->predicateformula_) f_theory_ck_pred_form->predicateformula_->accept(this);

}

void Skeleton::visitFTheoryCKKPredForm(FTheoryCKKPredForm *f_theory_ckk_pred_form)
{
  /* Code For FTheoryCKKPredForm Goes Here */

  if (f_theory_ckk_pred_form->allagents_) f_theory_ckk_pred_form->allagents_->accept(this);
  if (f_theory_ckk_pred_form->kpredicateformula_) f_theory_ckk_pred_form->kpredicateformula_->accept(this);

}

void Skeleton::visitFTheoryCKOrKPredForm(FTheoryCKOrKPredForm *f_theory_ck_or_k_pred_form)
{
  /* Code For FTheoryCKOrKPredForm Goes Here */

  if (f_theory_ck_or_k_pred_form->allagents_) f_theory_ck_or_k_pred_form->allagents_->accept(this);
  if (f_theory_ck_or_k_pred_form->kwpredicateformula_) f_theory_ck_or_k_pred_form->kwpredicateformula_->accept(this);

}

void Skeleton::visitFTheoryCKAndKPredForm(FTheoryCKAndKPredForm *f_theory_ck_and_k_pred_form)
{
  /* Code For FTheoryCKAndKPredForm Goes Here */

  if (f_theory_ck_and_k_pred_form->allagents_) f_theory_ck_and_k_pred_form->allagents_->accept(this);
  if (f_theory_ck_and_k_pred_form->notkwpredicateformula_) f_theory_ck_and_k_pred_form->notkwpredicateformula_->accept(this);

}

void Skeleton::visitKPredFormula(KPredFormula *k_pred_formula)
{
  /* Code For KPredFormula Goes Here */

  if (k_pred_formula->agentname_) k_pred_formula->agentname_->accept(this);
  if (k_pred_formula->predicateformula_) k_pred_formula->predicateformula_->accept(this);

}

void Skeleton::visitKWPredFormula(KWPredFormula *kw_pred_formula)
{
  /* Code For KWPredFormula Goes Here */

  if (kw_pred_formula->knowswhether_) kw_pred_formula->knowswhether_->accept(this);
  if (kw_pred_formula->predicateformula_) kw_pred_formula->predicateformula_->accept(this);

}

void Skeleton::visitNotKWPredFormula(NotKWPredFormula *not_kw_pred_formula)
{
  /* Code For NotKWPredFormula Goes Here */

  if (not_kw_pred_formula->knowswhether_) not_kw_pred_formula->knowswhether_->accept(this);
  if (not_kw_pred_formula->predicateformula_) not_kw_pred_formula->predicateformula_->accept(this);

}

void Skeleton::visitEPDDLInitialModel(EPDDLInitialModel *epddl_initial_model)
{
  /* Code For EPDDLInitialModel Goes Here */

  if (epddl_initial_model->modelname_) epddl_initial_model->modelname_->accept(this);
  if (epddl_initial_model->modelworldsdef_) epddl_initial_model->modelworldsdef_->accept(this);
  if (epddl_initial_model->modelreldef_) epddl_initial_model->modelreldef_->accept(this);
  if (epddl_initial_model->modelvaldef_) epddl_initial_model->modelvaldef_->accept(this);
  if (epddl_initial_model->modeldesdef_) epddl_initial_model->modeldesdef_->accept(this);

}

void Skeleton::visitModelWorlds(ModelWorlds *model_worlds)
{
  /* Code For ModelWorlds Goes Here */

  if (model_worlds->listworldname_) model_worlds->listworldname_->accept(this);

}

void Skeleton::visitModelRel(ModelRel *model_rel)
{
  /* Code For ModelRel Goes Here */

  if (model_rel->modelrelations_) model_rel->modelrelations_->accept(this);

}

void Skeleton::visitModelVal(ModelVal *model_val)
{
  /* Code For ModelVal Goes Here */

  if (model_val->modelvaluation_) model_val->modelvaluation_->accept(this);

}

void Skeleton::visitModelDes(ModelDes *model_des)
{
  /* Code For ModelDes Goes Here */

  if (model_des->listworldname_) model_des->listworldname_->accept(this);

}

void Skeleton::visitWorldsModelRel(WorldsModelRel *worlds_model_rel)
{
  /* Code For WorldsModelRel Goes Here */

  if (worlds_model_rel->listworldrelation_) worlds_model_rel->listworldrelation_->accept(this);

}

void Skeleton::visitTrivialModelRel(TrivialModelRel *trivial_model_rel)
{
  /* Code For TrivialModelRel Goes Here */

  if (trivial_model_rel->trivialdef_) trivial_model_rel->trivialdef_->accept(this);

}

void Skeleton::visitWorldsModelVal(WorldsModelVal *worlds_model_val)
{
  /* Code For WorldsModelVal Goes Here */

  if (worlds_model_val->listworldvaluation_) worlds_model_val->listworldvaluation_->accept(this);

}

void Skeleton::visitTrivialModelVal(TrivialModelVal *trivial_model_val)
{
  /* Code For TrivialModelVal Goes Here */

  if (trivial_model_val->trivialdef_) trivial_model_val->trivialdef_->accept(this);

}

void Skeleton::visitWorldRel(WorldRel *world_rel)
{
  /* Code For WorldRel Goes Here */

  if (world_rel->agentgroup_) world_rel->agentgroup_->accept(this);
  if (world_rel->listworldnamepair_) world_rel->listworldnamepair_->accept(this);

}

void Skeleton::visitTrivialWorldRel(TrivialWorldRel *trivial_world_rel)
{
  /* Code For TrivialWorldRel Goes Here */

  if (trivial_world_rel->agentgroup_) trivial_world_rel->agentgroup_->accept(this);
  if (trivial_world_rel->trivialdef_) trivial_world_rel->trivialdef_->accept(this);

}

void Skeleton::visitWorldPair(WorldPair *world_pair)
{
  /* Code For WorldPair Goes Here */

  if (world_pair->worldname_1) world_pair->worldname_1->accept(this);
  if (world_pair->worldname_2) world_pair->worldname_2->accept(this);

}

void Skeleton::visitWorldVal(WorldVal *world_val)
{
  /* Code For WorldVal Goes Here */

  if (world_val->worldname_) world_val->worldname_->accept(this);
  if (world_val->listliteral_) world_val->listliteral_->accept(this);

}

void Skeleton::visitEPDDLGoals(EPDDLGoals *epddl_goals)
{
  /* Code For EPDDLGoals Goes Here */

  if (epddl_goals->formula_) epddl_goals->formula_->accept(this);

}

void Skeleton::visitImplyFormula(ImplyFormula *imply_formula)
{
  /* Code For ImplyFormula Goes Here */

  if (imply_formula->formula_1) imply_formula->formula_1->accept(this);
  if (imply_formula->formula_2) imply_formula->formula_2->accept(this);

}

void Skeleton::visitOrFormula(OrFormula *or_formula)
{
  /* Code For OrFormula Goes Here */

  if (or_formula->formula_) or_formula->formula_->accept(this);
  if (or_formula->listformula_) or_formula->listformula_->accept(this);

}

void Skeleton::visitAndFormula(AndFormula *and_formula)
{
  /* Code For AndFormula Goes Here */

  if (and_formula->formula_) and_formula->formula_->accept(this);
  if (and_formula->listformula_) and_formula->listformula_->accept(this);

}

void Skeleton::visitNotFormula(NotFormula *not_formula)
{
  /* Code For NotFormula Goes Here */

  if (not_formula->formula_) not_formula->formula_->accept(this);

}

void Skeleton::visitModalFormula(ModalFormula *modal_formula)
{
  /* Code For ModalFormula Goes Here */

  if (modal_formula->modality_) modal_formula->modality_->accept(this);
  if (modal_formula->formula_) modal_formula->formula_->accept(this);

}

void Skeleton::visitVarFormula(VarFormula *var_formula)
{
  /* Code For VarFormula Goes Here */

  if (var_formula->variable_) var_formula->variable_->accept(this);

}

void Skeleton::visitAtmFormula(AtmFormula *atm_formula)
{
  /* Code For AtmFormula Goes Here */

  if (atm_formula->atomicformula_) atm_formula->atomicformula_->accept(this);

}

void Skeleton::visitAtmEqFormula(AtmEqFormula *atm_eq_formula)
{
  /* Code For AtmEqFormula Goes Here */

  if (atm_eq_formula->atomiceqformula_) atm_eq_formula->atomiceqformula_->accept(this);

}

void Skeleton::visitTrueFormula(TrueFormula *true_formula)
{
  /* Code For TrueFormula Goes Here */


}

void Skeleton::visitFalseFormula(FalseFormula *false_formula)
{
  /* Code For FalseFormula Goes Here */


}

void Skeleton::visitPredicate(Predicate *predicate)
{
  /* Code For Predicate Goes Here */

  if (predicate->predicatename_) predicate->predicatename_->accept(this);
  if (predicate->listmetaterm_) predicate->listmetaterm_->accept(this);

}

void Skeleton::visitEqFormula(EqFormula *eq_formula)
{
  /* Code For EqFormula Goes Here */

  if (eq_formula->term_1) eq_formula->term_1->accept(this);
  if (eq_formula->term_2) eq_formula->term_2->accept(this);

}

void Skeleton::visitNonTrivialFormula(NonTrivialFormula *non_trivial_formula)
{
  /* Code For NonTrivialFormula Goes Here */

  if (non_trivial_formula->formula_) non_trivial_formula->formula_->accept(this);

}

void Skeleton::visitTrivialFormula(TrivialFormula *trivial_formula)
{
  /* Code For TrivialFormula Goes Here */

  if (trivial_formula->trivialdef_) trivial_formula->trivialdef_->accept(this);

}

void Skeleton::visitEPDDLMetaTerm(EPDDLMetaTerm *epddl_meta_term)
{
  /* Code For EPDDLMetaTerm Goes Here */

  if (epddl_meta_term->term_) epddl_meta_term->term_->accept(this);

}

void Skeleton::visitEPDDLMetaTermAnonVar(EPDDLMetaTermAnonVar *epddl_meta_term_anon_var)
{
  /* Code For EPDDLMetaTermAnonVar Goes Here */

  if (epddl_meta_term_anon_var->anonvaragent_) epddl_meta_term_anon_var->anonvaragent_->accept(this);

}

void Skeleton::visitEPDDLGroundTerm(EPDDLGroundTerm *epddl_ground_term)
{
  /* Code For EPDDLGroundTerm Goes Here */

  if (epddl_ground_term->groundterm_) epddl_ground_term->groundterm_->accept(this);

}

void Skeleton::visitEPDDLTermVar(EPDDLTermVar *epddl_term_var)
{
  /* Code For EPDDLTermVar Goes Here */

  if (epddl_term_var->variable_) epddl_term_var->variable_->accept(this);

}

void Skeleton::visitEPDDLGroundTermName(EPDDLGroundTermName *epddl_ground_term_name)
{
  /* Code For EPDDLGroundTermName Goes Here */

  if (epddl_ground_term_name->name_) epddl_ground_term_name->name_->accept(this);

}

void Skeleton::visitEPDDLGroundTermAgName(EPDDLGroundTermAgName *epddl_ground_term_ag_name)
{
  /* Code For EPDDLGroundTermAgName Goes Here */

  if (epddl_ground_term_ag_name->agentname_) epddl_ground_term_ag_name->agentname_->accept(this);

}

void Skeleton::visitEPDDLLabeledMod(EPDDLLabeledMod *epddl_labeled_mod)
{
  /* Code For EPDDLLabeledMod Goes Here */

  if (epddl_labeled_mod->singlemodality_) epddl_labeled_mod->singlemodality_->accept(this);

}

void Skeleton::visitEPDDLLabeledGroupMod(EPDDLLabeledGroupMod *epddl_labeled_group_mod)
{
  /* Code For EPDDLLabeledGroupMod Goes Here */

  if (epddl_labeled_group_mod->groupmodality_) epddl_labeled_group_mod->groupmodality_->accept(this);

}

void Skeleton::visitLabBoxMod(LabBoxMod *lab_box_mod)
{
  /* Code For LabBoxMod Goes Here */

  if (lab_box_mod->modalitylabel_) lab_box_mod->modalitylabel_->accept(this);
  if (lab_box_mod->modalityagent_) lab_box_mod->modalityagent_->accept(this);

}

void Skeleton::visitLabDiamondMod(LabDiamondMod *lab_diamond_mod)
{
  /* Code For LabDiamondMod Goes Here */

  if (lab_diamond_mod->modalitylabel_) lab_diamond_mod->modalitylabel_->accept(this);
  if (lab_diamond_mod->modalityagent_) lab_diamond_mod->modalityagent_->accept(this);

}

void Skeleton::visitLabBoxGroupMod(LabBoxGroupMod *lab_box_group_mod)
{
  /* Code For LabBoxGroupMod Goes Here */

  if (lab_box_group_mod->modalitylabel_) lab_box_group_mod->modalitylabel_->accept(this);
  if (lab_box_group_mod->modalityagentgroup_) lab_box_group_mod->modalityagentgroup_->accept(this);

}

void Skeleton::visitLabDiamondGroupMod(LabDiamondGroupMod *lab_diamond_group_mod)
{
  /* Code For LabDiamondGroupMod Goes Here */

  if (lab_diamond_group_mod->modalitylabel_) lab_diamond_group_mod->modalitylabel_->accept(this);
  if (lab_diamond_group_mod->modalityagentgroup_) lab_diamond_group_mod->modalityagentgroup_->accept(this);

}

void Skeleton::visitModLabel(ModLabel *mod_label)
{
  /* Code For ModLabel Goes Here */

  if (mod_label->modalityname_) mod_label->modalityname_->accept(this);

}

void Skeleton::visitEmptyModLabel(EmptyModLabel *empty_mod_label)
{
  /* Code For EmptyModLabel Goes Here */


}

void Skeleton::visitKnowsWhetherMod(KnowsWhetherMod *knows_whether_mod)
{
  /* Code For KnowsWhetherMod Goes Here */

  if (knows_whether_mod->modalityname_) knows_whether_mod->modalityname_->accept(this);
  if (knows_whether_mod->agentname_) knows_whether_mod->agentname_->accept(this);

}

void Skeleton::visitPosLiteral(PosLiteral *pos_literal)
{
  /* Code For PosLiteral Goes Here */

  if (pos_literal->atomicformula_) pos_literal->atomicformula_->accept(this);

}

void Skeleton::visitNegLiteral(NegLiteral *neg_literal)
{
  /* Code For NegLiteral Goes Here */

  if (neg_literal->atomicformula_) neg_literal->atomicformula_->accept(this);

}

void Skeleton::visitAndCondFomula(AndCondFomula *and_cond_fomula)
{
  /* Code For AndCondFomula Goes Here */

  if (and_cond_fomula->condition_) and_cond_fomula->condition_->accept(this);
  if (and_cond_fomula->listcondition_) and_cond_fomula->listcondition_->accept(this);

}

void Skeleton::visitCondFomula(CondFomula *cond_fomula)
{
  /* Code For CondFomula Goes Here */

  if (cond_fomula->condition_) cond_fomula->condition_->accept(this);

}

void Skeleton::visitAtmCond(AtmCond *atm_cond)
{
  /* Code For AtmCond Goes Here */

  if (atm_cond->atomiccondition_) atm_cond->atomiccondition_->accept(this);

}

void Skeleton::visitNotAtmCond(NotAtmCond *not_atm_cond)
{
  /* Code For NotAtmCond Goes Here */

  if (not_atm_cond->atomiccondition_) not_atm_cond->atomiccondition_->accept(this);

}

void Skeleton::visitAtmCondPredicate(AtmCondPredicate *atm_cond_predicate)
{
  /* Code For AtmCondPredicate Goes Here */

  if (atm_cond_predicate->predicatename_) atm_cond_predicate->predicatename_->accept(this);
  if (atm_cond_predicate->listterm_) atm_cond_predicate->listterm_->accept(this);

}

void Skeleton::visitAtmCondEqFormula(AtmCondEqFormula *atm_cond_eq_formula)
{
  /* Code For AtmCondEqFormula Goes Here */

  if (atm_cond_eq_formula->term_1) atm_cond_eq_formula->term_1->accept(this);
  if (atm_cond_eq_formula->term_2) atm_cond_eq_formula->term_2->accept(this);

}

void Skeleton::visitImplyPredFormula(ImplyPredFormula *imply_pred_formula)
{
  /* Code For ImplyPredFormula Goes Here */

  if (imply_pred_formula->predicateformula_1) imply_pred_formula->predicateformula_1->accept(this);
  if (imply_pred_formula->predicateformula_2) imply_pred_formula->predicateformula_2->accept(this);

}

void Skeleton::visitOrPredFormula(OrPredFormula *or_pred_formula)
{
  /* Code For OrPredFormula Goes Here */

  if (or_pred_formula->predicateformula_) or_pred_formula->predicateformula_->accept(this);
  if (or_pred_formula->listpredicateformula_) or_pred_formula->listpredicateformula_->accept(this);

}

void Skeleton::visitAndPredFormula(AndPredFormula *and_pred_formula)
{
  /* Code For AndPredFormula Goes Here */

  if (and_pred_formula->predicateformula_) and_pred_formula->predicateformula_->accept(this);
  if (and_pred_formula->listpredicateformula_) and_pred_formula->listpredicateformula_->accept(this);

}

void Skeleton::visitNotPredFormula(NotPredFormula *not_pred_formula)
{
  /* Code For NotPredFormula Goes Here */

  if (not_pred_formula->predicateformula_) not_pred_formula->predicateformula_->accept(this);

}

void Skeleton::visitAtmPredFormula(AtmPredFormula *atm_pred_formula)
{
  /* Code For AtmPredFormula Goes Here */

  if (atm_pred_formula->predicatename_) atm_pred_formula->predicatename_->accept(this);
  if (atm_pred_formula->listgroundterm_) atm_pred_formula->listgroundterm_->accept(this);

}

void Skeleton::visitEPDDLGenericNameObj(EPDDLGenericNameObj *epddl_generic_name_obj)
{
  /* Code For EPDDLGenericNameObj Goes Here */

  if (epddl_generic_name_obj->name_) epddl_generic_name_obj->name_->accept(this);

}

void Skeleton::visitEPDDLGenericNameAg(EPDDLGenericNameAg *epddl_generic_name_ag)
{
  /* Code For EPDDLGenericNameAg Goes Here */

  if (epddl_generic_name_ag->agentname_) epddl_generic_name_ag->agentname_->accept(this);

}

void Skeleton::visitIdList(IdList *id_list)
{
  /* Code For IdList Goes Here */

  if (id_list->listname_) id_list->listname_->accept(this);

}

void Skeleton::visitTypedIdList(TypedIdList *typed_id_list)
{
  /* Code For TypedIdList Goes Here */

  if (typed_id_list->name_) typed_id_list->name_->accept(this);
  if (typed_id_list->listname_) typed_id_list->listname_->accept(this);
  if (typed_id_list->type_) typed_id_list->type_->accept(this);
  if (typed_id_list->typedidentlist_) typed_id_list->typedidentlist_->accept(this);

}

void Skeleton::visitVarList(VarList *var_list)
{
  /* Code For VarList Goes Here */

  if (var_list->listvariable_) var_list->listvariable_->accept(this);

}

void Skeleton::visitTypedVarList(TypedVarList *typed_var_list)
{
  /* Code For TypedVarList Goes Here */

  if (typed_var_list->variable_) typed_var_list->variable_->accept(this);
  if (typed_var_list->listvariable_) typed_var_list->listvariable_->accept(this);
  if (typed_var_list->type_) typed_var_list->type_->accept(this);
  if (typed_var_list->typedvariablelist_) typed_var_list->typedvariablelist_->accept(this);

}

void Skeleton::visitEPDDLPredicate(EPDDLPredicate *epddl_predicate)
{
  /* Code For EPDDLPredicate Goes Here */

  if (epddl_predicate->name_) epddl_predicate->name_->accept(this);

}

void Skeleton::visitEPDDLModAgent(EPDDLModAgent *epddl_mod_agent)
{
  /* Code For EPDDLModAgent Goes Here */

  if (epddl_mod_agent->agentname_) epddl_mod_agent->agentname_->accept(this);

}

void Skeleton::visitEPDDLModVarAgent(EPDDLModVarAgent *epddl_mod_var_agent)
{
  /* Code For EPDDLModVarAgent Goes Here */

  if (epddl_mod_var_agent->variable_) epddl_mod_var_agent->variable_->accept(this);

}

void Skeleton::visitEPDDLModAnonVarAgent(EPDDLModAnonVarAgent *epddl_mod_anon_var_agent)
{
  /* Code For EPDDLModAnonVarAgent Goes Here */

  if (epddl_mod_anon_var_agent->anonvaragent_) epddl_mod_anon_var_agent->anonvaragent_->accept(this);

}

void Skeleton::visitEPDDLModAllAgents(EPDDLModAllAgents *epddl_mod_all_agents)
{
  /* Code For EPDDLModAllAgents Goes Here */

  if (epddl_mod_all_agents->allagents_) epddl_mod_all_agents->allagents_->accept(this);

}

void Skeleton::visitEPDDLModAgList(EPDDLModAgList *epddl_mod_ag_list)
{
  /* Code For EPDDLModAgList Goes Here */

  if (epddl_mod_ag_list->modalityagent_) epddl_mod_ag_list->modalityagent_->accept(this);
  if (epddl_mod_ag_list->listmodalityagent_) epddl_mod_ag_list->listmodalityagent_->accept(this);

}

void Skeleton::visitEPDDLSingleAgentGroup(EPDDLSingleAgentGroup *epddl_single_agent_group)
{
  /* Code For EPDDLSingleAgentGroup Goes Here */

  if (epddl_single_agent_group->agentname_) epddl_single_agent_group->agentname_->accept(this);

}

void Skeleton::visitEPDDLAllAgentsGroup(EPDDLAllAgentsGroup *epddl_all_agents_group)
{
  /* Code For EPDDLAllAgentsGroup Goes Here */

  if (epddl_all_agents_group->allagents_) epddl_all_agents_group->allagents_->accept(this);

}

void Skeleton::visitEPDDLObsAgentGroup(EPDDLObsAgentGroup *epddl_obs_agent_group)
{
  /* Code For EPDDLObsAgentGroup Goes Here */

  if (epddl_obs_agent_group->agentname_) epddl_obs_agent_group->agentname_->accept(this);

}

void Skeleton::visitEPDDLObsAgent(EPDDLObsAgent *epddl_obs_agent)
{
  /* Code For EPDDLObsAgent Goes Here */

  if (epddl_obs_agent->agentname_) epddl_obs_agent->agentname_->accept(this);

}

void Skeleton::visitEPDDLObsAllAgents(EPDDLObsAllAgents *epddl_obs_all_agents)
{
  /* Code For EPDDLObsAllAgents Goes Here */

  if (epddl_obs_all_agents->allagents_) epddl_obs_all_agents->allagents_->accept(this);

}

void Skeleton::visitEPDDLObsVarAgent(EPDDLObsVarAgent *epddl_obs_var_agent)
{
  /* Code For EPDDLObsVarAgent Goes Here */

  if (epddl_obs_var_agent->variable_) epddl_obs_var_agent->variable_->accept(this);

}

void Skeleton::visitEPDDLObsAnonVarAgent(EPDDLObsAnonVarAgent *epddl_obs_anon_var_agent)
{
  /* Code For EPDDLObsAnonVarAgent Goes Here */

  if (epddl_obs_anon_var_agent->anonvaragent_) epddl_obs_anon_var_agent->anonvaragent_->accept(this);

}

void Skeleton::visitEPDDLAgentGroup(EPDDLAgentGroup *epddl_agent_group)
{
  /* Code For EPDDLAgentGroup Goes Here */

  if (epddl_agent_group->agentgroupname_) epddl_agent_group->agentgroupname_->accept(this);

}

void Skeleton::visitEPDDLAgentNameGroup(EPDDLAgentNameGroup *epddl_agent_name_group)
{
  /* Code For EPDDLAgentNameGroup Goes Here */

  if (epddl_agent_name_group->agentname_) epddl_agent_name_group->agentname_->accept(this);
  if (epddl_agent_name_group->listagentname_) epddl_agent_name_group->listagentname_->accept(this);

}

void Skeleton::visitEPDDLAllAgents(EPDDLAllAgents *epddl_all_agents)
{
  /* Code For EPDDLAllAgents Goes Here */


}

void Skeleton::visitEPDDLAnonVarAgent(EPDDLAnonVarAgent *epddl_anon_var_agent)
{
  /* Code For EPDDLAnonVarAgent Goes Here */


}

void Skeleton::visitEPDDLParam(EPDDLParam *epddl_param)
{
  /* Code For EPDDLParam Goes Here */

  if (epddl_param->variable_) epddl_param->variable_->accept(this);
  if (epddl_param->parametervalue_) epddl_param->parametervalue_->accept(this);

}

void Skeleton::visitEPDDLTermParam(EPDDLTermParam *epddl_term_param)
{
  /* Code For EPDDLTermParam Goes Here */

  if (epddl_term_param->term_) epddl_term_param->term_->accept(this);

}

void Skeleton::visitEPDDLFormulaParam(EPDDLFormulaParam *epddl_formula_param)
{
  /* Code For EPDDLFormulaParam Goes Here */

  if (epddl_formula_param->formula_) epddl_formula_param->formula_->accept(this);

}

void Skeleton::visitEPDDLPostParam(EPDDLPostParam *epddl_post_param)
{
  /* Code For EPDDLPostParam Goes Here */

  if (epddl_post_param->listpostparametervalue_) epddl_post_param->listpostparametervalue_->accept(this);

}

void Skeleton::visitPostParamForall(PostParamForall *post_param_forall)
{
  /* Code For PostParamForall Goes Here */

  if (post_param_forall->typedvariablelist_) post_param_forall->typedvariablelist_->accept(this);
  if (post_param_forall->listliteralpostcondition_) post_param_forall->listliteralpostcondition_->accept(this);

}

void Skeleton::visitPostParamLiteral(PostParamLiteral *post_param_literal)
{
  /* Code For PostParamLiteral Goes Here */

  if (post_param_literal->literalpostcondition_) post_param_literal->literalpostcondition_->accept(this);

}

void Skeleton::visitEPDDLTypeName(EPDDLTypeName *epddl_type_name)
{
  /* Code For EPDDLTypeName Goes Here */

  if (epddl_type_name->name_) epddl_type_name->name_->accept(this);

}

void Skeleton::visitEPDDLResType(EPDDLResType *epddl_res_type)
{
  /* Code For EPDDLResType Goes Here */

  if (epddl_res_type->reservedtype_) epddl_res_type->reservedtype_->accept(this);

}

void Skeleton::visitResAgentType(ResAgentType *res_agent_type)
{
  /* Code For ResAgentType Goes Here */


}

void Skeleton::visitPredicateType(PredicateType *predicate_type)
{
  /* Code For PredicateType Goes Here */


}

void Skeleton::visitLiteralType(LiteralType *literal_type)
{
  /* Code For LiteralType Goes Here */


}

void Skeleton::visitPredFormulaType(PredFormulaType *pred_formula_type)
{
  /* Code For PredFormulaType Goes Here */


}

void Skeleton::visitFormulaType(FormulaType *formula_type)
{
  /* Code For FormulaType Goes Here */


}

void Skeleton::visitPostconditionType(PostconditionType *postcondition_type)
{
  /* Code For PostconditionType Goes Here */


}

void Skeleton::visitEPDDLDomainName(EPDDLDomainName *epddl_domain_name)
{
  /* Code For EPDDLDomainName Goes Here */

  if (epddl_domain_name->name_) epddl_domain_name->name_->accept(this);

}

void Skeleton::visitEPDDLLibraryName(EPDDLLibraryName *epddl_library_name)
{
  /* Code For EPDDLLibraryName Goes Here */

  if (epddl_library_name->name_) epddl_library_name->name_->accept(this);

}

void Skeleton::visitEPDDLProblemName(EPDDLProblemName *epddl_problem_name)
{
  /* Code For EPDDLProblemName Goes Here */

  if (epddl_problem_name->name_) epddl_problem_name->name_->accept(this);

}

void Skeleton::visitEPDDLActionName(EPDDLActionName *epddl_action_name)
{
  /* Code For EPDDLActionName Goes Here */

  if (epddl_action_name->name_) epddl_action_name->name_->accept(this);

}

void Skeleton::visitEPDDLActTypeName(EPDDLActTypeName *epddl_act_type_name)
{
  /* Code For EPDDLActTypeName Goes Here */

  if (epddl_act_type_name->name_) epddl_act_type_name->name_->accept(this);

}

void Skeleton::visitEPDDLEventName(EPDDLEventName *epddl_event_name)
{
  /* Code For EPDDLEventName Goes Here */

  if (epddl_event_name->name_) epddl_event_name->name_->accept(this);

}

void Skeleton::visitEPDDLModelName(EPDDLModelName *epddl_model_name)
{
  /* Code For EPDDLModelName Goes Here */

  if (epddl_model_name->name_) epddl_model_name->name_->accept(this);

}

void Skeleton::visitEPDDLWorldName(EPDDLWorldName *epddl_world_name)
{
  /* Code For EPDDLWorldName Goes Here */

  if (epddl_world_name->name_) epddl_world_name->name_->accept(this);

}

void Skeleton::visitEPDDLReqDel(EPDDLReqDel *epddl_req_del)
{
  /* Code For EPDDLReqDel Goes Here */


}

void Skeleton::visitEPDDLReqTyping(EPDDLReqTyping *epddl_req_typing)
{
  /* Code For EPDDLReqTyping Goes Here */


}

void Skeleton::visitEPDDLReqEquality(EPDDLReqEquality *epddl_req_equality)
{
  /* Code For EPDDLReqEquality Goes Here */


}

void Skeleton::visitEPDDLReqParamList(EPDDLReqParamList *epddl_req_param_list)
{
  /* Code For EPDDLReqParamList Goes Here */


}

void Skeleton::visitEPDDLReqNegPre(EPDDLReqNegPre *epddl_req_neg_pre)
{
  /* Code For EPDDLReqNegPre Goes Here */


}

void Skeleton::visitEPDDLReqDisPre(EPDDLReqDisPre *epddl_req_dis_pre)
{
  /* Code For EPDDLReqDisPre Goes Here */


}

void Skeleton::visitEPDDLReqExiPre(EPDDLReqExiPre *epddl_req_exi_pre)
{
  /* Code For EPDDLReqExiPre Goes Here */


}

void Skeleton::visitEPDDLReqUniPre(EPDDLReqUniPre *epddl_req_uni_pre)
{
  /* Code For EPDDLReqUniPre Goes Here */


}

void Skeleton::visitEPDDLReqModPre(EPDDLReqModPre *epddl_req_mod_pre)
{
  /* Code For EPDDLReqModPre Goes Here */


}

void Skeleton::visitEPDDLReqModPost(EPDDLReqModPost *epddl_req_mod_post)
{
  /* Code For EPDDLReqModPost Goes Here */


}

void Skeleton::visitEPDDLReqModalities(EPDDLReqModalities *epddl_req_modalities)
{
  /* Code For EPDDLReqModalities Goes Here */


}

void Skeleton::visitEPDDLReqOnticChange(EPDDLReqOnticChange *epddl_req_ontic_change)
{
  /* Code For EPDDLReqOnticChange Goes Here */


}

void Skeleton::visitEPDDLReqCK(EPDDLReqCK *epddl_req_ck)
{
  /* Code For EPDDLReqCK Goes Here */


}

void Skeleton::visitEPDDLReqDynCK(EPDDLReqDynCK *epddl_req_dyn_ck)
{
  /* Code For EPDDLReqDynCK Goes Here */


}

void Skeleton::visitEPDDLReqMAStar(EPDDLReqMAStar *epddl_req_ma_star)
{
  /* Code For EPDDLReqMAStar Goes Here */


}

void Skeleton::visitEPDDLReqOntic(EPDDLReqOntic *epddl_req_ontic)
{
  /* Code For EPDDLReqOntic Goes Here */


}

void Skeleton::visitEPDDLReqSensing(EPDDLReqSensing *epddl_req_sensing)
{
  /* Code For EPDDLReqSensing Goes Here */


}

void Skeleton::visitEPDDLReqAnnouncement(EPDDLReqAnnouncement *epddl_req_announcement)
{
  /* Code For EPDDLReqAnnouncement Goes Here */


}

void Skeleton::visitEPDDLReqFTheory(EPDDLReqFTheory *epddl_req_f_theory)
{
  /* Code For EPDDLReqFTheory Goes Here */


}

void Skeleton::visitEPDDLReqMaxPreDepth(EPDDLReqMaxPreDepth *epddl_req_max_pre_depth)
{
  /* Code For EPDDLReqMaxPreDepth Goes Here */

  visitInteger(epddl_req_max_pre_depth->integer_);

}

void Skeleton::visitEPDDLReqMaxPostDepth(EPDDLReqMaxPostDepth *epddl_req_max_post_depth)
{
  /* Code For EPDDLReqMaxPostDepth Goes Here */

  visitInteger(epddl_req_max_post_depth->integer_);

}

void Skeleton::visitEPDDLReqMaxDepth(EPDDLReqMaxDepth *epddl_req_max_depth)
{
  /* Code For EPDDLReqMaxDepth Goes Here */

  visitInteger(epddl_req_max_depth->integer_);

}

void Skeleton::visitEPDDLTrivialDef(EPDDLTrivialDef *epddl_trivial_def)
{
  /* Code For EPDDLTrivialDef Goes Here */


}


void Skeleton::visitListDomainItemDef(ListDomainItemDef *list_domain_item_def)
{
  for (ListDomainItemDef::iterator i = list_domain_item_def->begin() ; i != list_domain_item_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListPredicateDef(ListPredicateDef *list_predicate_def)
{
  for (ListPredicateDef::iterator i = list_predicate_def->begin() ; i != list_predicate_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListObsConditionDef(ListObsConditionDef *list_obs_condition_def)
{
  for (ListObsConditionDef::iterator i = list_obs_condition_def->begin() ; i != list_obs_condition_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListLibraryItemDef(ListLibraryItemDef *list_library_item_def)
{
  for (ListLibraryItemDef::iterator i = list_library_item_def->begin() ; i != list_library_item_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListEventSignature(ListEventSignature *list_event_signature)
{
  for (ListEventSignature::iterator i = list_event_signature->begin() ; i != list_event_signature->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListEventRelation(ListEventRelation *list_event_relation)
{
  for (ListEventRelation::iterator i = list_event_relation->begin() ; i != list_event_relation->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListEventNamePair(ListEventNamePair *list_event_name_pair)
{
  for (ListEventNamePair::iterator i = list_event_name_pair->begin() ; i != list_event_name_pair->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListPostcondition(ListPostcondition *list_postcondition)
{
  for (ListPostcondition::iterator i = list_postcondition->begin() ; i != list_postcondition->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListLiteralPostcondition(ListLiteralPostcondition *list_literal_postcondition)
{
  for (ListLiteralPostcondition::iterator i = list_literal_postcondition->begin() ; i != list_literal_postcondition->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListProblemItemDef(ListProblemItemDef *list_problem_item_def)
{
  for (ListProblemItemDef::iterator i = list_problem_item_def->begin() ; i != list_problem_item_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListAgentGroupDef(ListAgentGroupDef *list_agent_group_def)
{
  for (ListAgentGroupDef::iterator i = list_agent_group_def->begin() ; i != list_agent_group_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListFactDef(ListFactDef *list_fact_def)
{
  for (ListFactDef::iterator i = list_fact_def->begin() ; i != list_fact_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListFTheoryFormula(ListFTheoryFormula *list_f_theory_formula)
{
  for (ListFTheoryFormula::iterator i = list_f_theory_formula->begin() ; i != list_f_theory_formula->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListWorldRelation(ListWorldRelation *list_world_relation)
{
  for (ListWorldRelation::iterator i = list_world_relation->begin() ; i != list_world_relation->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListWorldNamePair(ListWorldNamePair *list_world_name_pair)
{
  for (ListWorldNamePair::iterator i = list_world_name_pair->begin() ; i != list_world_name_pair->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListWorldValuation(ListWorldValuation *list_world_valuation)
{
  for (ListWorldValuation::iterator i = list_world_valuation->begin() ; i != list_world_valuation->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListFormula(ListFormula *list_formula)
{
  for (ListFormula::iterator i = list_formula->begin() ; i != list_formula->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListMetaTerm(ListMetaTerm *list_meta_term)
{
  for (ListMetaTerm::iterator i = list_meta_term->begin() ; i != list_meta_term->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListTerm(ListTerm *list_term)
{
  for (ListTerm::iterator i = list_term->begin() ; i != list_term->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListGroundTerm(ListGroundTerm *list_ground_term)
{
  for (ListGroundTerm::iterator i = list_ground_term->begin() ; i != list_ground_term->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListLiteral(ListLiteral *list_literal)
{
  for (ListLiteral::iterator i = list_literal->begin() ; i != list_literal->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListCondition(ListCondition *list_condition)
{
  for (ListCondition::iterator i = list_condition->begin() ; i != list_condition->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListPredicateFormula(ListPredicateFormula *list_predicate_formula)
{
  for (ListPredicateFormula::iterator i = list_predicate_formula->begin() ; i != list_predicate_formula->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListGenericName(ListGenericName *list_generic_name)
{
  for (ListGenericName::iterator i = list_generic_name->begin() ; i != list_generic_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListModalityAgent(ListModalityAgent *list_modality_agent)
{
  for (ListModalityAgent::iterator i = list_modality_agent->begin() ; i != list_modality_agent->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListObservingAgentGroup(ListObservingAgentGroup *list_observing_agent_group)
{
  for (ListObservingAgentGroup::iterator i = list_observing_agent_group->begin() ; i != list_observing_agent_group->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListParameter(ListParameter *list_parameter)
{
  for (ListParameter::iterator i = list_parameter->begin() ; i != list_parameter->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListPostParameterValue(ListPostParameterValue *list_post_parameter_value)
{
  for (ListPostParameterValue::iterator i = list_post_parameter_value->begin() ; i != list_post_parameter_value->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListLibraryName(ListLibraryName *list_library_name)
{
  for (ListLibraryName::iterator i = list_library_name->begin() ; i != list_library_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListEventName(ListEventName *list_event_name)
{
  for (ListEventName::iterator i = list_event_name->begin() ; i != list_event_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListWorldName(ListWorldName *list_world_name)
{
  for (ListWorldName::iterator i = list_world_name->begin() ; i != list_world_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListRequireKey(ListRequireKey *list_require_key)
{
  for (ListRequireKey::iterator i = list_require_key->begin() ; i != list_require_key->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListName(ListName *list_name)
{
  for (ListName::iterator i = list_name->begin() ; i != list_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListAgentName(ListAgentName *list_agent_name)
{
  for (ListAgentName::iterator i = list_agent_name->begin() ; i != list_agent_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListModalityName(ListModalityName *list_modality_name)
{
  for (ListModalityName::iterator i = list_modality_name->begin() ; i != list_modality_name->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListVariable(ListVariable *list_variable)
{
  for (ListVariable::iterator i = list_variable->begin() ; i != list_variable->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



